### ISSUE TITLE
Problem building Sophus using visual studio

### ISSUE THREAD

**Issue by zenified** [strasdat/Sophus#10]
Hi I am trying to build Sophus on visual studio 10 after generating the files using cmake, and was presented with the following error

-multiple  error C2144: syntax error : 'int' should be preceded by ';' for the statement "typedef RxSO3Group<double> ScSO3 EIGEN_DEPRECATED;" 

- error C2065: 'M_PI_2' : undeclared identifier	for the statement "  tangent_vec.push_back(Tangent(M_PI_2,M_PI_2,0.0));" in test_203.cpp

For the first error, the syntax for the typedef is not what I am familiar with, however I noticed that the same declaration was done across multiple files thus concluded that it was not a typography error. However if this is the case, I am unsure as to what causes the syntax error.

Thanks

**Comment by strasdat** [comment]
I merged from Steve, so closing out this issue.
