### ISSUE TITLE
Random rotation

### ISSUE THREAD

**Issue by versatran01** [strasdat/Sophus#100]
Is there a function that generates a random member of SO3?
Like something described in 
Effective sampling and distance metrics for 3d rigid body path planning, J. Kuffner, ICRA 2004.

**Comment by strasdat** [comment]
There is a straight-forward way to sample uniformaly from a sphere:

**Comment by versatran01** [comment]
Thanks for the answer. I was just wondering if you can add this to the interface?

**Comment by strasdat** [comment]
Will do.

**Comment by strasdat** [comment]
I implemented this for SO(2) and SO(3). See #114.
