### ISSUE TITLE
Warning: calling a host function from a host device via Sophus::SE3f::Log

### ISSUE THREAD

**Issue by JmanVtrus** [strasdat/Sophus#107]
Greetings,

I am hoping to get some insight on a compiler warning regarding a host device function which gets the tangent space via the Log function. The warning is:

> /workspace/Sophus/sophus/so3.hpp(569): warning: calling a __host__ function from a __host__ __device__ function is not allowed
>           detected during:
>             instantiation of "Sophus::SO3GroupBase<Derived>::Tangent Sophus::SO3GroupBase<Derived>::logAndTheta(const Sophus::SO3Group<Sophus::SO3GroupBase<Derived>::Scalar, 0> &, Sophus::SO3GroupBase<Derived>::Scalar *) [with Derived=Sophus::SO3Group<float, 0>]" 
> /workspace/Sophus/sophus/se3.hpp(653): here
>             instantiation of "Sophus::SE3GroupBase<Derived>::Tangent Sophus::SE3GroupBase<Derived>::log(const Sophus::SE3Group<Sophus::SE3GroupBase<Derived>::Scalar, 0> &) [with Derived=Sophus::SE3Group<float, 0>]" 
> /workspace/Sophus/sophus/se3.hpp(235): here
>             instantiation of "Sophus::SE3GroupBase<Derived>::Tangent Sophus::SE3GroupBase<Derived>::log() const [with Derived=Sophus::SE3Group<float, 0>]" 
> /workspace/vtrus/lib_vtrus_core/include/vtruscore/math/Utils.h(65): here

The Utils function that has the warning is a global c inline function:

```

__host__ __device__
inline bool IsTransformationWithinBounds(const Sophus::SE3f& T_rl, const float maxDistanceMeters, const float maxAngleDegrees)
{
    Eigen::Matrix<float, 6, 1> T_rl_ln = T_rl.log();
    float distance = core::float3(T_rl_ln[0], T_rl_ln[1], T_rl_ln[2]).norm();
    float angle = Rad2Deg(core::float3(T_rl_ln[3], T_rl_ln[4], T_rl_ln[5]).norm());

    if(distance <= maxDistanceMeters && angle <= maxAngleDegrees)
    {
        return true;
    }

    return false;
}
}

```
I see the function is marked as an EIGEN_DEVICE_FUNCTION, but the line:
Tanget upsilon_omega;   
resolves to typedef Matrix<Scalar,DoF,1> Tangent;

Do note that I can call log and pass in an Eigen::Matrix<float, 6, 1> rather than the Sophus::SE3f and have no warnings, but I would like to get some thoughts regardless. I appreciate any suggestions or thoughts

**Comment by strasdat** [comment]
I believe this is fixed by now; please reopen if this is not the case.
