### ISSUE TITLE
Is it possible to support Blaze?

### ISSUE THREAD

**Issue by vincent-hui** [strasdat/Sophus#109]
Is it possible to support blaze too? Users can choose use Eigen or Blaze in compile time. There is a matrix type called hybridmatrix in Blaze. Hybridmatrix should be more efficient than Eigen's dynamic matrix. The blaze::HybridMatrix class template combines the flexibility of a dynamically sized matrix with the efficiency and performance of a fixed size matrix.  

https://bitbucket.org/blaze-lib/blaze/wiki/Matrix%20Types#!hybridmatrix
https://bitbucket.org/blaze-lib/blaze

**Comment by strasdat** [comment]
I never heard of blaze. Looks interesting though. 
Does blaze handle alignment issues more elegantly than Eigen? Why don't you create a branch using blaze and then we can see from there?

Did you ever try blaze within. A cuda kernel?

**Comment by strasdat** [comment]
Hm, on second thought, it seems quite unlikely that I will support Blaze any time soon. Blaze looks sufficiently similar to Eigen, and Eigen has much more users than Blaze.

Happy to revisit this, if Blaze gained more traction (e.g. is being picked up as underlying math library by major open source projects).
