### ISSUE TITLE
No initialization (Like Eigen)

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#112]
Eigen does not initialize via default constructors (for performance reasons??). Instead, they provide initializer methods like `Zero()` and `Identity()`.

Would it make sense to be consistent with this in Sophus and, for instance, have `SO3::Identity()`, `SE3::Identity()`, etc and not default initialize?

I can see this being a significant enough change to maybe have to be done during a major version increment since some users probably rely on this default initialization.

**Comment by strasdat** [comment]
Personally, I do not like c++/Eigen's philosophy to default to the efficient version, instead to the save one:

```
int i;
std::cout << i << std::endl; // reading uninitialized value
```

In practice, there are only few cases where this is performance bottleneck, and we really don't want to initialize the variable ``i``.

In a perfect world

```
int i; // initializes to 0
int j [[uninitialized]]; // leaves is uninitialized
```

I can't change c++ built in types, but I can write libraries in such a way.

Long story short, I'd be okay to add a 

```
static SE3<...> uninitilized();
``` 

factory which leaves the element uninitialized, if there is demand for it.

**Comment by ibtaylor** [comment]
Yeah, what I a mess. I thought this was sort of the reason for the new syntax `int j{};` http://en.cppreference.com/w/cpp/language/value_initialization

I guess I was thinking about the situation where you have a `std::vector` of `SE3d` and want to `resize()` vs `reserve()/push_back()`. Afaik, you're forced to pass over and initialize all of the memory during the `resize` even if you plan on initializing with a loop after if your default constructor fully initializes.

**Comment by strasdat** [comment]
I'd say ``reserve()/push_back()`` is clearly the better approach in general, since you don't have to worry about how expensive the default constructor is for a type Foo.
