### ISSUE TITLE
SE3 translation() map type missing Options

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#113]
Seems like `Options` is missing from the `Map` type
https://github.com/strasdat/Sophus/blob/d8aa1c54c463b5b3d5e6f9e28302f3124b101751/sophus/se3.hpp#L720
https://github.com/strasdat/Sophus/blob/d8aa1c54c463b5b3d5e6f9e28302f3124b101751/sophus/se3.hpp#L726

Hit a compile error when attempting to use an `Eigen::Map<SE3d,Eigen::Aligned>`
Adding in the `Options` to the `Map` seemed to allow it to compile at least.

**Comment by strasdat** [comment]
@ibtaylor good catch! Do you want to write a patch and open a PR?

**Comment by ibtaylor** [comment]
Sure. I'll make one soon. Been offline from the flu.

**Comment by strasdat** [comment]
#140
