### ISSUE TITLE
Version number missing in cmake config

### ISSUE THREAD

**Issue by tomifischer** [strasdat/Sophus#123]
I was compiling using cmake and trying to include Sophus in the process, but wanted to require a specific version (1.0). When evaluating

`FIND_PACKAGE(Sophus 1.0 REQUIRED)`

the cmake process fails:

```
CMake Error at CMakeLists.txt:16 (FIND_PACKAGE):
Could not find a configuration file for package "Sophus" that is compatible
with requested version "1.0".

The following configuration files were considered but not accepted:

  /usr/local/lib/cmake/Sophus/SophusConfig.cmake, version: unknown

-- Configuring incomplete, errors occurred!
```
I'm not an expert, but probably just the version number missing in SophusConfig.cmake.in

**Comment by NikolausDemmel** [comment]
Have you seen #120? Does that maybe solve your issue?

**Comment by strasdat** [comment]
Now we have a version number.

**Comment by tomifischer** [comment]
Thank you! Sorry, I didn't get to test the PR.
