### ISSUE TITLE
Ros Release

### ISSUE THREAD

**Issue by stonier** [strasdat/Sophus#13]
We're interested in doing a ros release (either native catkin or ros 3rd party) of Sophus. If you're still interested in supporting Sophus let us know and we'll make some pull requests here, otherwise we'll fork it, release and attempt to support contributions from the community from the fork.

Before I forget....it's a nice library! Thanks for putting this out there in the wild!

**Comment by strasdat** [comment]
Daniel, I won't be able to maintain it currently, so please go ahead and for it.

**Comment by stonier** [comment]
Ok, thanks for the quick heads up.

**Comment by strasdat** [comment]
I took over maintenance of Sophus again. Just to let you know.

**Comment by stonier** [comment]
Great, will you take up maintenance of the ros debs as well?

**Comment by strasdat** [comment]
Sorry, will only be able to maintain upstream, i.e. this repo.

**Comment by stonier** [comment]
That's fine.
