### ISSUE TITLE
Testing failed in Debug mode

### ISSUE THREAD

**Issue by jaehak** [strasdat/Sophus#14]
Hi,

Compilation of Sophus in Debug mode such as -O0 or without any flags for optimization seems leading to failing such as test_se3.cpp. My system is Ubuntu 14 on 64bit. The Eigen library I am using is version 3.2.0-8.

Do you have any idea why it happens or could you tell me if I did something wrong? Of course, this testing works well when it is compiled in Release mode (i.e. -O3). 

For compiling in debug mode, I ran ccmake and changed CMAKE_BUILD_TYPE for Debug. Then running tests (test_se3) shows as follows:
$ test_se3 
Test SE3 

Double tests: 
G - exp(log(G))
Test case: 1
          0           0           0    -1.66561
          0           0           0    -1.43697
          0           0           0 4.44089e-16
          0           0           0           0

G - exp(log(G))
Test case: 4
          0           0           0 -4.1366e-21
          0           0           0 2.77784e-10
          0           0           0           0
          0           0           0           0

G - exp(log(G))
Test case: 5
           0            0            0 -1.66667e-13
           0            0            0 -0.000833335
           0            0            0            0
           0            0            0            0

G - exp(log(G))
Test case: 6
          0           0           0           0
          0           0           0  -0.0821279
          0           0           0 3.53395e-16
          0           0           0           0

G - exp(log(G))
Test case: 8
 1.11022e-16            0  1.11022e-16     -3.96847
           0            0  5.55112e-17      10.9571
 1.11022e-16            0            0 -1.77636e-15
           0            0            0            0

failed!

I appreicate any answer.

**Comment by emanuelev** [comment]
Hi, I ran into the same problem. There is a side effect (probably coming from Eigen) in the exponential mapping function which doesn't show up when you compile with O3. The quick fix is to change the function in this way:

inline static
  const SE3Group<Scalar> exp(const Tangent & a) {
    const Matrix<Scalar,3,1> & omega = a.template tail<3>();

    Scalar theta;
    const SO3Group<Scalar> & so3
        = SO3Group<Scalar>::expAndTheta(omega, &theta);

    Matrix<Scalar,3,3>  Omega = SO3Group<Scalar>::hat(omega);
//    const Matrix<Scalar,3,3> & Omega_sq = Omega*Omega;
    Matrix<Scalar,3,3> V;

    if(theta<SophusConstants<Scalar>::epsilon()) {
      V = so3.matrix();
      //Note: That is an accurate expansion!
    } else {
      Scalar theta_sq = theta*theta;

      V = (Matrix<Scalar,3,3>::Identity()
           + (static_cast<Scalar>(1)-std::cos(theta))/(theta_sq)*Omega
           + (((theta-std::sin(theta))/(theta_sq*theta)) * (Omega*Omega)));
    }
    return SE3Group<Scalar>(so3,V*a.template head<3>());
  }

I'll initiate a pull request to have this fixed.

Hope this helps,

Emanuele

**Comment by jaehak** [comment]
Hi Emanuele,

Thank you for your answer and solution. I tried your fix, and It completely solved my issue as well. I confirm the "test_se3" has passed the test successfully in both Debug and Release mode.

Thanks.

Jae-Hak

**Comment by strasdat** [comment]
That should be fixed now, thanks.
