### ISSUE TITLE
Add an overload to operator* that operates on Points?

### ISSUE THREAD

**Issue by versatran01** [strasdat/Sophus#143]
Do you think it's a good idea to add an overload to operator* that works on Points?
It would look like something like this
```
Points SO3::operator*(Points const& points) const {
    return matrix() * points;
}
```
where Points is Matrix3 in this particular case.

**Comment by strasdat** [comment]
Don't think it has to much value.

Typing ``so3 * points`` versus ``so3.matrix() * points`` only saves you a few characters and the latter is more explicit/clear what is going on.
