### ISSUE TITLE
provide package.xml for ROS compatibility?

### ISSUE THREAD

**Issue by v01d** [strasdat/Sophus#145]
Hi,
I was wondering if you would be willing to include a package.xml for ROS compatibility. This allows to simply clone your repo into the catkin workspace and compile with no problems. The one from stonier's fork of your repo works directly. I think it is only needed to add an install rule of this file in the CMakeLists.txt, which would also allow for releasing this package into ROS directly.

**Comment by strasdat** [comment]
Make a PR and I merge it if I don't see any issue.

**Comment by v01d** [comment]
I added the PR #152

**Comment by strasdat** [comment]
done
