### ISSUE TITLE
Order of parameters in Dx_exp_x output jacobian for SE3

### ISSUE THREAD

**Issue by Trexter** [strasdat/Sophus#148]
I have been trying to figure out the order of the parameters (columns). Does it go: qx, qy, qz, qw, x, y, z?
Further, just to make sure, is the order of the rows is: vx, vy, vz, wx, wy, wz. where v is the translation part.

**Comment by strasdat** [comment]
Look at params: https://github.com/strasdat/Sophus/blob/master/sophus/se3.hpp#L361

Note there is a potential convention bug (rows vs cols): Will be looking into it shortly: https://github.com/strasdat/Sophus/issues/148

**Comment by Trexter** [comment]
Thanks
