### ISSUE TITLE
How to convert SE3 object to Rotation and translation matrix 

### ISSUE THREAD

**Issue by dharma-kc** [strasdat/Sophus#150]
Could you please look at this:

https://stackoverflow.com/questions/49295175/create-sophusse3-object-from-eigen-rotation-and-translation-matrix-and-go-back

I am trying to get the rotation and translation from SE3, but I get different values for rotation matrix. Thank you.

**Comment by NikolausDemmel** [comment]
Well looks like what you give as input is not actually a rotation matrix. You should read up on the properties of rotation matrices (SO(3) group). I.e. they are orthogonal and have determinant 1.

**Comment by dharma-kc** [comment]
Oh ya-Thanks for the reply. I knew that but forgot somehow. Thank you so much. I will try with that and try again.

**Comment by dharma-kc** [comment]
Thank you, 
I created the valid rotation matrix using following equations and it works now.

Eigen::Matrix3d R = Eigen::AngleAxisd(M_PI/2, Eigen::Vector3d(0, 0, 1)).toRotationMatrix(); 	// PI/2 rotation along z axis. Thank you so much.
