### ISSUE TITLE
ceres / storage order

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#151]
https://github.com/strasdat/Sophus/blob/00f3fd91c153ef04432ae26450080fd3357f421d/test/ceres/local_parameterization_se3.hpp#L31-L37
uses default eigen ordering (configurable at compile-time).. but it should explicity use row major based on
http://ceres-solver.org/nnls_modeling.html?highlight=local%20parameterization#_CPPv2NK5ceres21LocalParameterization15ComputeJacobianEPKdPd
https://github.com/ceres-solver/ceres-solver/blob/9026d69d1ce1e0bcd21debd54a38246d85c7c6e4/internal/ceres/local_parameterization.cc#L127
https://github.com/ceres-solver/ceres-solver/blob/78d49f46825ce2f8c7fb040b373bcd638729ced2/include/ceres/internal/eigen.h#L44

```cpp
static constexpr int kGlobalSize = SE3d::num_parameters;
static constexpr int kLocalSize = SE3d::DoF;
Eigen::Map<Matrix<double, kGlobalSize, kLocalSize, Eigen::RowMajor> > jacobian(jacobian_raw);
jacobian = T.Dx_this_mul_exp_x_at_0().transpose(); // transposing just because of its return value
```
seems like dimensions of `Dx_this_mul_exp_x_at_0` are reversed? shouldn't number of columns be based on the size of DoF (size of x)
https://en.wikipedia.org/wiki/Jacobian_matrix_and_determinant

**Comment by strasdat** [comment]
If this is true, this is a major issue. Thanks for pointing it out!

**Comment by ibtaylor** [comment]
Might be good in travis to have a build with and without `EIGEN_DEFAULT_TO_ROW_MAJOR` defined.. https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html

Could help find cases that should be explicit, like when using `Map`.

The above case may happen to work by default, but it would probably fail if you compiled with the mentioned define.

**Comment by strasdat** [comment]
Awesome suggestion!

**Comment by ibtaylor** [comment]
I can confirm that compiling with `EIGEN_DEFAULT_TO_ROW_MAJOR` causes `test_ceres_se3` to fail. Using the changes I described above, the test passes when compiling with and without `EIGEN_DEFAULT_TO_ROW_MAJOR`.

**Comment by strasdat** [comment]
@ibtaylor, I believe I fixed the storage order/Jacobian convention in this PR #156, but looking forward to your review ;)

I did not add the EIGEN_DEFAULT_TO_ROW_MAJOR option yet to the Travis CI build matrix.

**Comment by strasdat** [comment]
Added the EIGEN_DEFAULT_TO_ROW_MAJOR to CI, all builds passed and PR is merged.

**Comment by ibtaylor** [comment]
I haven't tried it yet. Seems like the right direction though. I'll give feedback if I run into any issues.

Thanks.
