### ISSUE TITLE
SE3f.Data() Calling a host function from Host device 

### ISSUE THREAD

**Issue by JmanVtrus** [strasdat/Sophus#154]
Greetings all, 

I am getting a compiler warning on one of my internal classes that uses the .data call and am curious as to why ? The .data header shows it being an EIGEN_DEVICE_FUNC:

The warning:

> Sophus/sophus/so3.hpp(166): warning: calling a __host__ function from a __host__ __device__ function is not allowed
>           detected during:
>             instantiation of "const Sophus::SO3GroupBase<Derived>::Scalar *Sophus::SO3GroupBase<Derived>::data() const [with Derived=Sophus::SO3Group<float, 0>]" 
> Sophus/sophus/se3.hpp(833): here
>             instantiation of "const Sophus::SE3Group<_Scalar, _Options>::Scalar *Sophus::SE3Group<_Scalar, _Options>::data() const [with _Scalar=float, _Options=0]" 
> geometry/Matrix.h(50): here

My function:
```
    __host__ __device__
    Matrix( const Sophus::SE3f & T_w_l )
    {
        float *tt2 = (float*)T_w_l.data(); // This line causes the warning 
        float qx = tt2[0];
        float qy = tt2[1];
        float qz = tt2[2];
        float qw = tt2[3];

        _00(1.0f - 2.0f*qy*qy - 2.0f*qz*qz);
        _01(2.0f*qx*qy + 2.0f*qz*qw);
        _02(2.0f*qx*qz - 2.0f*qy*qw);
        _03(0);
        _10(2.0f*qx*qy - 2.0f*qz*qw);
        _11(1.0f - 2.0f*qx*qx - 2.0f*qz*qz);
        _12(2.0f*qy*qz + 2.0f*qx*qw);
        _13(0);
        _20(2.0f*qx*qz + 2.0f*qy*qw);
        _21(2.0f*qy*qz - 2.0f*qx*qw);
        _22(1.0f - 2.0f*qx*qx - 2.0f*qy*qy);
        _23(0);
        _30(tt2[4]);
        _31(tt2[5]);
        _32(tt2[6]);
        _33(1);
    }
```

The se3 header:

>   /**
>    * \returns const pointer to internal data
>    *
>    * Const version of data().
>    */
>   EIGEN_DEVICE_FUNC EIGEN_STRONG_INLINE
>   const Scalar* data() const {
>     // so3_ and translation_ are layed out sequentially with no padding
>     return so3_.data();
>   }

**Comment by JmanVtrus** [comment]
The se3 is a packed buffer right ? Can I safely just cast it to a float* direct from memory  which will cause no warnings:

`float *tt2 = (float*)&T_w_l;`

**Comment by strasdat** [comment]
old...
