### ISSUE TITLE
 question about derivative of exp(x) wrt. x

### ISSUE THREAD

**Issue by MerlotQ** [strasdat/Sophus#157]
I guess exp(x) is a 3x3 matrix. Why is the Jacobian a 3x4 matrix?

**Comment by jlblancoc** [comment]
I **think** it's like that because it's the derivate wrt a quaternion representation of rotation...

**Comment by NikolausDemmel** [comment]
I agree with @jlblancoc. Even if you assume you are talking about SO(3), depending what `exp(x)` exactly you mean, the Jacobian could be any of 9x9, 9x3, 4x4, 4x3 and possibly others as well. Note that the order recently changed to follow standard conventions: https://github.com/strasdat/Sophus/issues/151#issuecomment-381382490
