### ISSUE TITLE
Implementing hat vee operation with Sophus Python

### ISSUE THREAD

**Issue by HTLife** [strasdat/Sophus#158]
@arntanguy @strasdat  I'm using Sophus Python to do se3 SE3 conversion.  And I wanna make sure I understand hat and vee operation of se3 correctly.

My workflow is like:
1. (x y z Quaternion) ==>  se3, R^4x4 ==(vee)==> se3, R^6
2. se3, R^6 ==(Exponential mapping)==> SE(3)
3. Accumulate SE(3)
4. SE(3) ==> (x y zQuaternion)

Because the exp() function in step 2 only takes R^6 representation of se3, I need to convert the matrix (R^4x4) output to R^6 first.  There is no vee operation in Sophus python, so I just reference the C++ implementation.

However, in [se3.hpp](https://github.com/strasdat/Sophus/blob/master/sophus/se3.hpp#L907) the vee operation only accepts zero diagonal matrix, which makes the conversion irreversible.

a (R^4x4 of se3)

a ==(vee)==> b ==(hat)==> a'
Which a != a' after conversion.

Example:
```python
def xyzQuaternion2se3(x,y,z,ww,wx,wy,wz):
    trans = Matrix([x,y,z])
    
    q_real = ww
    q_img = Matrix([wx, wy, wz])
    q = Quaternion(q_real,q_img)
    R = So3(q)
    
    RT = Se3(R, trans)
    
    return RT

RT_se3 = xyzQuaternion2se3(9,10,13,-0.764,0.002,0.612,-0.204)


M = RT_se3.matrix()
print(M)
"""
Matrix(
[ [0.167680000000000, -0.309264000000000, -0.935952000000000, 9], 
  [0.314160000000000, 0.916760000000000, -0.246640000000000, 10], 
  [0.934320000000000, -0.252752000000000, 0.250904000000000, 13], 
  [0, 0, 0, 1]])
"""
v = Se3.vee(M)
print(v)
# Matrix([[9], [10], [13], [-0.252752000000000], [-0.935952000000000], [0.314160000000000]])

Se3.hat(v)
"""
Matrix([
[       0,  -0.31416, -0.935952,  9],
[ 0.31416,         0,  0.252752, 10],
[0.935952, -0.252752,         0, 13],
[       0,         0,         0,  0]])
"""
```

Is this the correct representation conversion(which will loss information)?

**Comment by NikolausDemmel** [comment]
Looks like in the first step you get an SE(3) 4x4 matrix, not se(3). I guess `vee` only makes sense for se(3) elements, which have 0 on the diagonal.

**Comment by HTLife** [comment]
@NikolausDemmel You are right! 
Can I ask you that where can I find the related definition(document) about 0 diagonal?

**Comment by NikolausDemmel** [comment]
@HTLife, the vee operator acts on Lie algebra elements and those have 0 on the diagonal. See for example its introduction in https://www.doc.ic.ac.uk/~ajd/Publications/strasdat_phd2012.pdf on page 46.

**Comment by HTLife** [comment]
@NikolausDemmel Thanks for the documentation with detail, it really helps.
Now it makes my background understanding more complete.
