### ISSUE TITLE
Use problem about Sophus

### ISSUE THREAD

**Issue by zhaoxuhui** [strasdat/Sophus#160]
I install and use Sophus as the instructions on the Internet.But the project always fails to build.This confused me a few days.Here is what I did.

1.Download and compile Sophus

`
git clone https://github.com/strasdat/Sophus.git

cd Sophus
git checkout a621ff
mkdir build
cd build
cmake ..
make
`

2.Include Sophus in my project
I write in CMakelist as this.

`
find_package( Sophus REQUIRED )
include_directories( ${Sophus_INCLUDE_DIRS} )

add_executable(useSophus useSophus.cpp)
target_link_libraries(useSophus ${Sophus_LIBRARIES} )
`

But it seems that CMake can't find the package.So I use `make install` to install Sophus.Then I can find the Sophus files in /usr/local/include/sophus.This time CMake can find the package.But new problems comes.I include Sophus like this.

`
#include "sophus/so3.h"
#include "sophus/se3.h"
`

But it says "undefined reference".After I searched on the Internet,I know that this is because the compiler can't find the cpp file.So I copy all the cpp and h file to the dir /usr/local/include/sophus.And include them in my code.

`
#include "sophus/so3.h"
#include "sophus/se3.h"
#include "sophus/se3.cpp"
#include "sophus/so3.cpp"
`

This time it works,my program can run normally.

But in my another project, it doesn't work well again.It says `Sophus::SO3::matrix() const' is defined many times.I dont't know how to deal with this.If I delete cpp include ,it will say "undefined reference",I include cpp file,it will say "defined many times".

I don't know what the problem is.Is that I didn't install the Sophus correctly or use it in a wrong way?Maybe this problem is very easy for you.But I just learn to use Sophus,so it may be a little hard for me.Hope to your reply.Thanks!

**Comment by ChadHsing** [comment]
I meet the same problem, have you solved it after then?

**Comment by zhaoxuhui** [comment]
Yeah. I solved the problem and recorded the solution in my blog.
[http://zhaoxuhui.top/blog/2018/04/27/LieGroup&Sophus.html](url)
The blog is in Chinese, so if you can read it you may solve the problem too. Or you may connect me again for more information.
