### ISSUE TITLE
How to use Sim3?

### ISSUE THREAD

**Issue by vicdxxx** [strasdat/Sophus#165]
Hi Guys,
I want to use Sim3, but I do not know why I cannot construct a Sim3 Object.
I do see this in sim.h:

  Sim3                       (double s,
                              const Matrix3d & R,
                              const Vector3d & t);

But error occurred when I use it:
undefined reference to `Sophus::Sim3::Sim3(double, Eigen::Matrix<double, 3, 3, 0, 3, 3> const&, Eigen::Matrix<double, 3, 1, 0, 3, 1> const&)'
And   SIM3_R=SIM3_R.from_SE3(SE3_R); do work.
My test code snippet:

    AngleAxisd aa=AngleAxisd(30.0/180.*M_PI,  Vector3d(0,0,1));
    const Matrix3d R=aa.matrix();
    Quaterniond q(aa);
    const Vector3d t(1,0,0);
    double s=2.0;
    Sim3 SIM3_R;
    Sim3 SIM3_R1(s,R,t);
    Sim3 SIM3_R2;
    SE3 SE3_R(R,t);
    SIM3_R=SIM3_R.from_SE3(SE3_R);

I have try Matrix, Quaternion and  SO3 with translate to construct Sim3 Objects.
I saw the source code, my way seems reasonable?
And does that need a scale parameter?
Any suggestion is highly appreciated!
Vic

**Comment by strasdat** [comment]
This is old. Please reopen, if there is still a question now :)
