### ISSUE TITLE
Lower required cmake version

### ISSUE THREAD

**Issue by arntanguy** [strasdat/Sophus#170]
Any reason why cmake 3.4 is required? Some people are unfortunately stuck with using old versions of ubuntu (14.04...) and this unusually high requirement makes it annoying to compile, as we have to manually edit the CMakeLists to go back to a lower required version.

As far as I can tell, everything works fine with anything above cmake 2.8.

**Comment by sergiud** [comment]
You can always install a newer version of CMake locally.

How did you ensure that "everything" works with CMake version 2.8? `CMakeLists.txt` and the generated package configuration require commands that are not even available in CMake 2.8. Hence, I doubt your test was thorough.

**Comment by arntanguy** [comment]
It works with 3.2.2 for sure, that's the version I have locally.

**Comment by sergiud** [comment]
Looking through `CMakeLists.txt`, Sophus could even work with CMake 3.1. However, this definitely needs some testing using the minimal CMake version and not just by guessing.

**Comment by strasdat** [comment]
old...
