### ISSUE TITLE
Compilation error with LLVM and user define ensureFailed function

### ISSUE THREAD

**Issue by ojwoodford** [strasdat/Sophus#171]
The 4 lines `SOPHUS_ENSURE(is_valid_, "must be valid");` in common.hpp cause a compilation error when compiled using LLVM on Mac. The error is:

> Pasting formed '("must be valid"', an invalid preprocessing token

The error is fixed by removing the ## from the macro definition in that file.

**Comment by ojwoodford** [comment]
Does the change suggested above break any other compilations? Is this tested for in the unit tests?

**Comment by NikolausDemmel** [comment]
I use it w/o issue on macos with clang. Maybe it is a matter of version (I'm on Sierra, other's use it fine on Mojave) with the latest default clang for those macos versions from Apple.

Maybe it is a matter of defines. Which of the defines of SOPHUS_ENSURE are used in your compilation? For me it's the one using `defaultEnsure`.

**Comment by strasdat** [comment]
I believe this is fixed now. (if not, please reopen)
