### ISSUE TITLE
build failure with SOPHUS_DISABLE_ENSURES

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#177]
Currently the build errors out because of `-Werror` on unused variables when `SOPHUS_DISABLE_ENSURES` is defined.

`det` is unused.
https://github.com/strasdat/Sophus/blob/b475c0a81a197ff8ea6bdcf8df8a2f5a7b1da879/sophus/geometry.hpp#L99-L103
`at` is unused
https://github.com/strasdat/Sophus/blob/b475c0a81a197ff8ea6bdcf8df8a2f5a7b1da879/sophus/types.hpp#L115-L118

The continuous integration should probably also build with the equivalent of `cmake  -DCMAKE_CXX_FLAGS="-DSOPHUS_DISABLE_ENSURES"` so that this doesn't happen again in the future.

**Comment by strasdat** [comment]
Sure, feel free to create a PR>

**Comment by strasdat** [comment]
Fixed.
