### ISSUE TITLE
Unnecessary const creates compiler warning

### ISSUE THREAD

**Issue by ojwoodford** [strasdat/Sophus#19]
Compilation warning from clang:

In file included from ../thirdparty/Sophus/se3.hpp:27:
../thirdparty/Sophus/so3.hpp:801:3: warning: 'const' qualifier on reference type 'ConstQuaternionReference' (aka 'const typename internal::traits<Map<const SO3Group<type-parameter-0-0, 0>, _Options, Stride<0, 0> > >::QuaternionType &') has no effect [-Wignored-qualifiers]
  const ConstQuaternionReference unit_quaternion() const {
  ^~~~~~
1 warning generated.

Solution: remove the const (which is unnecessary).

**Comment by strasdat** [comment]
This is fixed/obsolete.
