### ISSUE TITLE
No member data() for Eigen::Map specialization

### ISSUE THREAD

**Issue by versatran01** [strasdat/Sophus#190]
Hi I was trying to do something like:

```code
Vector10 T; // some initialization
Eigen::Map<SE3> M(T.data()); // interpret the first 7 elements as SE3
// Do something with M.data(), but does not compile
// But the following works;
auto p = M.so3().data();
```
Is this because `data()` is not implemented in the specialization of Map? How can I fix this?

**Comment by NikolausDemmel** [comment]
Is `data()` implemented for Eigen's `Map<Matrix<...>>` specialization? I don't see a reason why it shouldn't be there. It guess you could just add it in the following two places:

https://github.com/strasdat/Sophus/blob/26c200265e2eb3d76e5ab00a99ada686d6a80d15/sophus/se3.hpp#L1034

https://github.com/strasdat/Sophus/blob/26c200265e2eb3d76e5ab00a99ada686d6a80d15/sophus/se3.hpp#L1075

And then maybe also the similarly for the other classes.
