### ISSUE TITLE
Online Docs

### ISSUE THREAD

**Issue by amiller27** [strasdat/Sophus#191]
I know this project used to have Doxygen documentation, which was removed in #49.  I've written a Python script which transforms the code in its current form so that Doxygen can generate documentation with everything in monospace, so that the ascii art is preserved, like this:
![image](https://user-images.githubusercontent.com/4535296/52984919-8387dc80-33bf-11e9-864b-f43a5ed375fc.png)

I'm thinking of implementing something automated which autogenerates the Doxygen-compatible version of the code, runs Doxygen, and publishes the result, but I wanted to check if that's something you would accept as a PR.  It could be integrated with the Travis build and published on GitHub Pages, but I would go a different route if something like that wouldn't get merged here.

**Comment by strasdat** [comment]
This sounds awesome. I totally would accept such PR.

**Comment by strasdat** [comment]
@amiller27, just curious, are there any modern alternatives to doxygen?

cldoc looks interesting and seems to do what your python script does and more:
http://jessevdk.github.io/cldoc/

Also natural docs looks similar, but seems to be a little less mature:
https://www.naturaldocs.org/getting_started/documenting_your_code/

Honestly, I'd prefer to reuse an existing project - ideally with large community support - instead of a home brew solution.

**Comment by amiller27** [comment]
I totally agree that if there's a better solution already we should use it.  I'm not super up to date on all the documentation tools out there, I picked Doxygen because it's the one I was familiar with and the one you had used before.  It seems like most of the alternatives would require some in-source indicators that you want the output to be monospace just like Doxygen does.

The Python script I have is dead simple, it's 54 lines and just wraps the doc comments in verbatim tags.  I wasn't sure you opposed you were to polluting the in-source documentation, but the output is still very readable; the generated output looks like this:
```
  /*! \verbatim
   Returns closest SE3 given arbirary 4x4 matrix.
  
  \endverbatim */
  template <class S = Scalar>
  SOPHUS_FUNC static enable_if_t<std::is_floating_point<S>::value, SE3>
  fitToSE3(Matrix4<Scalar> const& T) {
    return SE3(SO3<Scalar>::fitToSO3(T.template block<3, 3>(0, 0)),
               T.template block<3, 1>(0, 3));
  }

  /*! \verbatim
   Returns the ith infinitesimal generators of SE(3).
  
   The infinitesimal generators of SE(3) are:
  
           |  0  0  0  1 |
     G_0 = |  0  0  0  0 |
           |  0  0  0  0 |
           |  0  0  0  0 |
  
           |  0  0  0  0 |
     G_1 = |  0  0  0  1 |
           |  0  0  0  0 |
           |  0  0  0  0 |
  
           |  0  0  0  0 |
     G_2 = |  0  0  0  0 |
           |  0  0  0  1 |
           |  0  0  0  0 |
  
           |  0  0  0  0 |
     G_3 = |  0  0 -1  0 |
           |  0  1  0  0 |
           |  0  0  0  0 |
  
           |  0  0  1  0 |
     G_4 = |  0  0  0  0 |
           | -1  0  0  0 |
           |  0  0  0  0 |
  
           |  0 -1  0  0 |
     G_5 = |  1  0  0  0 |
           |  0  0  0  0 |
           |  0  0  0  0 |
  
   Precondition: ``i`` must be in [0, 5].
  
  \endverbatim */
  SOPHUS_FUNC static Transformation generator(int i) {
    SOPHUS_ENSURE(i >= 0 && i <= 5, "i should be in range [0,5].");
    Tangent e;
    e.setZero();
    e[i] = Scalar(1);
    return hat(e);
  }
```

**Comment by strasdat** [comment]
I found yet another one: https://github.com/foonathan/standardese
Seems to be used by the c++ standard/boost community.

**Comment by amiller27** [comment]
So where exactly do you want me to go from here?  It seems like any of these documentation generators would still require some tag in the source to treat the ascii art as monospace, which would mean either running my script or modifying the source.

I'd probably still pick Doxygen out of the options you mentioned just because it seems more well-established, especially for C++, but if you'd rather use something else I can do that instead.

**Comment by strasdat** [comment]
@amiller27 , thank you for your suggestions and inspirations. I decided that I prefer to setup an initial documentation skeleton myself. Possibly I will go with https://exhale.readthedocs.io/en/latest/.

Once, the initial version is setup, I'm most definitely open to pull request to improve it etc.

**Comment by strasdat** [comment]
Here you go: https://strasdat.github.io/Sophus/index.html

**Comment by amiller27** [comment]
That looks great, thanks for doing that!  One thing, not sure if you noticed this, but it seems to handle monospace blocks indicated by indentation (e.g. SE3::vee) but not by the triple-backticks (e.g. SE3::generator).  Essentially I'm saying the ones with the triple backticks look broken.

**Comment by strasdat** [comment]
Yeah, I noticed that too. I updated travis-ci to xenial and hence got a newer doxygen version. Now this renders correctly.

One thing which does not work yet is python autodoc. Works just fine locally on my machine, for some reason travis ci worker does not produce it...

**Comment by strasdat** [comment]
@amiller27, FYI I'm using doxyrest now instead of exhale. Provides similar functionality, but the overall design seems more clean.

**Comment by diplodocuslongus** [comment]
> Here you go: https://strasdat.github.io/Sophus/index.html

Does any one know where is the doc now?
