### ISSUE TITLE
Applying sim3 to se3

### ISSUE THREAD

**Issue by NikolausDemmel** [strasdat/Sophus#193]
Similar to applying a sim3 transformation to 3-vectors, you can also consider applying it to se3 poses (e.g. when you want to transform camera poses from one world frame to another). For this I define the following `*` operator.

```cpp
// apply sim3 to se3 transformation (returns se3)
template <typename Sim3Derived, typename SE3Derived>
Sophus::SE3<typename Eigen::ScalarBinaryOpTraits<
    typename Sim3Derived::Scalar, typename SE3Derived::Scalar>::ReturnType>
operator*(const Sophus::Sim3Base<Sim3Derived>& a,
          const Sophus::SE3Base<SE3Derived>& b) {
  return {a.quaternion().normalized() * b.unit_quaternion(),
          a.rxso3() * b.translation() + a.translation()};
}
```

Would it make sense to include upstream? In which file should it go (I guess you don't want to include `se3.hpp` in `sim3.hpp` to make it a member of `Sim3`)?

**Comment by strasdat** [comment]
I'd say this is too specific to include into Sophus...

**Comment by NikolausDemmel** [comment]
Ok sure, no problems.
