### ISSUE TITLE
target include directories incomplete after first cmake call

### ISSUE THREAD

**Issue by martinruenz** [strasdat/Sophus#194]
Hi Hauke,

I noticed something weird when using Sophus as a dependency today. The target’s exported `INTERFACE_INCLUDE_DIRECTORIES` property is only containing `/usr/include/eigen3` but not the directories of Sophus – which results in  a failing build of my application, since no header file is found. However, when running `cmake` a second time, `${_IMPORT_PREFIX}/include` is appended to `INTERFACE_INCLUDE_DIRECTORIES` and the build works fine.

Not being a cmake expert I couldn’t figure out why this happens, yet. It might even be a cmake bug. (I tried cmake `3.14.0` and `3.10.2`). Any idea?

This snippet shows what’s going wrong:

```
git clone https://github.com/strasdat/Sophus.git
cd Sophus       
mkdir build1
mkdir build2
cd build1
cmake -DCMAKE_INSTALL_PREFIX=../install1 -DBUILD_TESTS=OFF ..
make install
cd ..

cd build2
cmake -DCMAKE_INSTALL_PREFIX=../install2 -DBUILD_TESTS=OFF ..
cmake -DCMAKE_INSTALL_PREFIX=../install2 -DBUILD_TESTS=OFF ..
make install
cd ..

diff \
install1/share/sophus/cmake/SophusTargets.cmake \
install2/share/sophus/cmake/SophusTargets.cmake 
```

Which produces the output:
```
58c58
<   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3"
---
>   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3;${_IMPORT_PREFIX}/include"
```

Naturally, the same `diff` shows up when running:
```
diff \
build1/CMakeFiles/Export/share/sophus/cmake/SophusTargets.cmake \
build2/CMakeFiles/Export/share/sophus/cmake/SophusTargets.cmake
58c58
<   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3"
---
>   INTERFACE_INCLUDE_DIRECTORIES "/usr/include/eigen3;${_IMPORT_PREFIX}/include"
```

**Comment by strasdat** [comment]
I'm not a CMake expert either...

**Comment by pvangoor** [comment]
I have tried to replicate this bug with cmake version 3.10.2 but when I run `diff` nothing shows up.

**Comment by martinruenz** [comment]
That's reassuring. I am pretty sure the issue is CMake and not Sophus related. Which OS were you running? I probably used Ubuntu 18, but maybe Fedora 29.

Maybe we should close the issue here and I'll report this to the CMake team if I can still reproduce this.

**Comment by pvangoor** [comment]
I'm on ubuntu 18.04. I might give a go at cmake 3.14 later.

**Comment by jobrud** [comment]
I came across the same problem with my project and finally I found the reason for that issue. The "include(GNUInstallDirs)" should be done before any use of  `CMAKE_INSTALL_..` variables. I saw that you correct this already with a commit https://github.com/strasdat/Sophus/commit/20136081108a4a3751a54b3d955af216814e9d27.

**Comment by martinruenz** [comment]
Great find! @jobrud

These kind of side-effects in cmake can really be a time killer.
