### ISSUE TITLE
Warning on explicitly defaulted functions when compiled with CUDA

### ISSUE THREAD

**Issue by yangxingrui** [strasdat/Sophus#198]
Hi,
first of all, love your work, really helpful!

I am getting loads of warning when compiling Sophus with CUDA10.1. such as:
`so2.hpp(357): warning: __device__ annotation is ignored on a function("SO2") that is explicitly defaulted on its first declaration`

I guess is mainly because starting form CUDA7.0 nvcc is supporting [N2346](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2007/n2346.htm) and is not necessary  to mark defaulted functions as both `__host__` and `__device__` ?

Currently I just delete the `SOPHUS_FUNC` annotation from the headers but I don't think is the best way to do it as it would cause troubles for older CUDA versions, also I don't see in anywhere that Sophus referenced CUDA headers so I can't find a way to extract CUDA versions at compile time. And the defined macro `EIGEN_CUDACC_VER` in eigen seems to have 0 value regardless of whether eigen is configured with CUDA or not.

Would appreciate your thoughts on this, thank you!

**Comment by anuppari** [comment]
This is still an issue, can you re-open?
