### ISSUE TITLE
Sophus_INCLUDE_DIRS is empty

### ISSUE THREAD

**Issue by vencewill** [strasdat/Sophus#224]
I tried to include Sophus in cmake using `include_directories( ${Sophus_INCLUDE_DIRS} )`. But this doesnt seem to work, causing `#include <sophus/se3.hpp>` not found. If i change it to `/usr/local/include` my project was built perfectly.

Or is this a new feature or something? Cuz I tried only include the directory without `target_link_libraries` the `HelloSO3` still works perfectly.

**Comment by sergiud** [comment]
See #247 for correct usage.
