### ISSUE TITLE
Sophus Build error 

### ISSUE THREAD

**Issue by shivSD** [strasdat/Sophus#229]
I'm getting the following error when i try to build the sophus master branch code. Please, can you help me to resolve this issue.

OS: Ubuntu 16.04
eigen: 3.3

undersource directory created "build" directory
cd build
cmake ..
make

Error: 
**/home/Downloads/Sophus/sophus/so2.hpp:101:40: error: ‘ScalarBinaryOpTraits’ in namespace ‘Eigen’ does not name a template type
   using ReturnScalar = typename Eigen::ScalarBinaryOpTraits<
                                        ^
/home/Downloads/Sophus/sophus/so2.hpp:105:26: error: ‘ReturnScalar’ was not declared in this scope
   using SO2Product = SO2<ReturnScalar<OtherDerived>>;
                          ^
/home/Downloads/Sophus/sophus/so2.hpp:105:39: error: template argument 1 is invalid
   using SO2Product = SO2<ReturnScalar<OtherDerived>>;
                                       ^
/home/Downloads/Sophus/sophus/so2.hpp:108:32: error: ‘ReturnScalar’ was not declared in this scope
   using PointProduct = Vector2<ReturnScalar<PointDerived>>;**

**Comment by zhanima** [comment]
same error. did you fix it？

**Comment by plumewind** [comment]
Me too，did you fix it？

**Comment by strasdat** [comment]
I'm accepting pull request to fix this - as long as it does not break CI, etc.
