### ISSUE TITLE
Run linux tests with eigen 3.3.7, gcc 9

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#241]
The linux tests don't seem to be running against eigen 3.3.7, but the osx tests are.
https://github.com/strasdat/Sophus/blob/d63ad09177f6b99ba605d684bac7f4b8d6820f5a/scripts/install_linux_deps.sh#L10

related #240

**Comment by ibtaylor** [comment]
Seems like testing against gcc 9 would be good too since that seemed to surface some issues.

**Comment by strasdat** [comment]
accepting PRs to update the CI scripts.
