### ISSUE TITLE
Uninitialized `so2_` in `SE2` default constructor

### ISSUE THREAD

**Issue by browdus** [strasdat/Sophus#244]
The default constructor for `SE2` currently initializes the translation value (`translation_`), but not the rotation value (`so2_`). This means anyone calling the default constructor does not get an identity, but rather an undefined and potentially invalid (e.g. [0, 0], [nan, nan], etc.) rotation.

See: https://github.com/strasdat/Sophus/blob/master/sophus/se2.hpp#L729

Potential fix: initialize `so2_` to `SO2<Scalar>()`, similar to `SE2::trans()`. I'd be willing to raise a PR if the fix looks ok.

**Comment by NikolausDemmel** [comment]
I think it should be ok.

For classes, the default constructor (`SO2<Scalar>()`) is called automatically if you don't specify anything in the initializer list. Only basic member types like `int` may stay uninitialized.

**Comment by NikolausDemmel** [comment]
PS: For translation it is needed, because by default, Eigen does not initialize matrices in the default constructor.

**Comment by browdus** [comment]
We've seen issues crop up in our codebase due to using the default constructor without an initializer list. For example, someone might pass `SO2<double>()` to a function, thinking it represents an identity (as mentioned in the source). Likewise, we've seen patterns like `SO2<double> foo = SO2<double>()` being used to initialize a member variable, again thinking the default constructor gives you an identity. This would probably be easier to catch if the instance was completely uninitialized, but because the translation gets set, issues can go undetected for a while.

**Comment by NikolausDemmel** [comment]
Hm... I'm no C++ standard expert, but to my understanding adding the initializer `so2_(SO2<Scalar>())` would be exactly equivalent to not adding it at all. In both cases `so_` is initialized with the the default constructor. (In the former case there might be possibility of a copy/move in unoptimized code, not sure... Anyway, wouldn't change the result).

> For example, someone might pass SO2<double>() to a function, thinking it represents an identity (as mentioned in the source). Likewise, we've seen patterns like SO2<double> foo = SO2<double>() being used to initialize a member variable, again thinking the default constructor gives you an identity. This would probably be easier to catch if the instance was completely uninitialized, but because the translation gets set, issues can go undetected for a while.

I agree 100%, however, what I'm saying is that from a quick glance at the code it seems to me that rotation **is** initialized to identity (via the default constructor of SO2).

**Comment by browdus** [comment]
Sorry, replace `SO2` with `SE2` in my previous comment. I'll play around with it some more, and let you know what I find. Thanks for the quick help!

**Comment by NikolausDemmel** [comment]
> Sorry, replace SO2 with SE2 in my previous comment. I'll play around with it some more, and let you know what I find. Thanks for the quick help!

Sure, my reply referred to SE2. Maybe you can come up with a minimal reproducible example that shows the issue you were seeing.

**Comment by browdus** [comment]
After some more digging, it looks like the issue is in our code. I'll admit, my C++ isn't great. Initializing the SE2 seemed to alleviate the issue, but it was apparently coincidence. Thanks for the help, and sorry for the wild goose chase!

**Comment by NikolausDemmel** [comment]
Sure. Happy coding!
