### ISSUE TITLE
CMake find_package() problems 

### ISSUE THREAD

**Issue by niebayes** [strasdat/Sophus#247]
I compiled and installed sophus like this: 
`mkdir build && cd build` 
`cmake ..`
`sudo make install` 
I'm pretty sure there's no problems during compiling and installation. 
My problem is: the find_package() command could find sophus and set the variable Sophus_FOUND to True. But when it comes to another loaded variables, for instance Sophus_INCLUDE_DIRS and Sophus_LIBRARIES, CMake simply set them to None such that the output of `message(${Sophus_INCLUDE_DIRS})` would be empty. 
I resolved this issue by explicitly calling this command `include_directories(<absolute_path_to_sophus_header_files>)`. But I don't know why the find_package() command doesn't work. Can anyone explain this ?! 
My operating systen is macOS 10.15 and CMake version 3.17.

**Comment by sergiud** [comment]
Legacy style CMake variables such as `Sophus_INCLUDE_DIRS` are not defined by the package config anymore (rightly so). You need to link against the `Sophus::Sophus` target.

**Comment by niebayes** [comment]
@sergiud I've read the CMakeLists.txt of Sophus, and what I found might be useful is: `target_link_libraries(sophus INTERFACE Eigen3::Eigen)`
Yet I still don't know HOW to link against the `Sophus::Sophus` target. 
Can you clarify it ?

**Comment by niebayes** [comment]
@sergiud I solved this issue in accordance with #120 , like this:
`find_package(Sophus 1.0)
...
target_link_libraries(target Sophus::Sophus)`
Thank you!
