### ISSUE TITLE
Visual Studio Cpp error.

### ISSUE THREAD

**Issue by Hamsas** [strasdat/Sophus#248]
First, thank you for sharing the codes!

All Cmakes builds were successful in my VS 2019. 
Yet, all cpp files carry one error shown below...

E0992	command-line error: invalid macro definition: =	HelloSO3.exe (examples\HelloSO3.exe) - x64-Debug	\Sophus-master\examples\HelloSO3.cpp	1	

Not only this Hello file but also all cpp files carry the exactly same error...
It seems that my visual studio has some issue with clang format? 
Your code is very neat... I don't know why I get those errors for all cpp files when all other cmakes and hpp are fine...
Any suggestions are appreciated!

**Comment by strasdat** [comment]
Hey @Hamsas if you find a solution, and if it does not break CI, I'm more than happy to merge a corresponding pull request.
