### ISSUE TITLE
Mac terminal library not found for -lSophus::Sophus

### ISSUE THREAD

**Issue by lilala9720** [strasdat/Sophus#250]
When I was building my own program, I incident with this error:
ld: library not found for -lSophus::Sophus
clang: error: linker command failed with exit code 1 (use -v to see invocation)

is there anything I can do?

**Comment by sergiud** [comment]
You need to call
```cmake
find_package (Sophus REQUIRED NO_MODULE)
```
 in your `CMakeLists.txt`.

**Comment by strasdat** [comment]
Let's use the community Q&A forum for these type of discussions in the future: https://github.com/strasdat/Sophus/discussions/categories/q-a
