### ISSUE TITLE
Probably a very naive question, how can I copy the value in a SE3 object to a non-SE3 object?

### ISSUE THREAD

**Issue by yrq0208** [strasdat/Sophus#251]
Hi all,

I got a probably very naive question, which is how can I copy the value in a SE3 object to a non-SE3 object, for example a C++ array or an Eigen Vector object?

![SE3](https://user-images.githubusercontent.com/34848593/89452883-46034480-d756-11ea-9059-d9bcba7d05e7.png)

So I got an SE3 object called T_cur_ref here, which looks like a 2*3 matrix after I print it. I found out I can use the translation() method to get the second row of T_cur_ref into an Eigen Vector3d object, but I can't do something similar to the first row value. If I use so3() it will extract the first row into a SO3 object, which is not what I want. If I use rotation_matrix() method it will produce a 3*3 matrix, which I assume it is where the first row values are coming from, but this 3*3 matrix it is still not what I want. 

So is there any way I can extract the first row values in T_cur_ref into an array or an Eigen Vector? Like what I have done with the second row values? Or is it simply not doable (except calculating the first row values from the rotation matrix myself, by hand)?

Thanks in advance.

Best regards,
Ruiqi

**Comment by NikolausDemmel** [comment]
Try this:

```
Sophus::SE3d foo = ...;

// just quaternion:
Eigen::Vector4d bar = foo.so3().params();

// or everything in one:
Eigen::Matrix<double, 7, 1> baz = foo.params();
```

**Comment by yrq0208** [comment]
Hi @NikolausDemmel,

Thanks for the reply.

However it seems that my systems complains that ‘SE3d’ is not a member of ‘Sophus’ and ‘class Sophus::SO3’ has no member named ‘params’, as well as ‘class Sophus::SE3’ has no member named ‘params’

**Comment by NikolausDemmel** [comment]
Maybe you have an older version of Sophus then.

This might still work for the quaternion:

```
foo.so3().unit_quaternion().coeffs()
```

**Comment by yrq0208** [comment]
I make it through the compilation, however the result doesn't seem consistent with the value in the SE3 object? Did I miss something (sorry I am really not a computer vision expert)?

![SO3](https://user-images.githubusercontent.com/34848593/89459695-f9713680-d760-11ea-8dd3-bb376b4f08f6.png)

Regarding the Sophus version, I just git clone from this repo.

**Comment by NikolausDemmel** [comment]
Well you were using the master version, `Sophus::SE3d` would be defined, and `params()` also: https://github.com/strasdat/Sophus/blob/master/sophus/se3.hpp#L12

Not sure how you are printing it. Without knowing what verison you are using, it's hard to tell what is going on. Since it's 3 values for rotation, maybe it's the output of `foo.log()`, or `foo.so3().log()`...

**Comment by yrq0208** [comment]
Ok my bad, I don't think I am using the master version, I am following instruction on this website when installing Sophus: https://github.com/uzh-rpg/rpg_svo/wiki/Installation:-Plain-CMake-(No-ROS)

I just use std cout function to print the results.

Is there any way I can check the output of foo.log() or foo.so3().log()?

**Comment by NikolausDemmel** [comment]
Thats a super old version from 2012.

You can output it just like Sophus does... And yes, it is using `log()` on the so3 part:

https://github.com/strasdat/Sophus/blob/a621ff2e56c56c839a6c40418d42c3c254424b5c/sophus/se3.h#L158-L163

https://github.com/strasdat/Sophus/blob/a621ff2e56c56c839a6c40418d42c3c254424b5c/sophus/so3.h#L122-L128

**Comment by yrq0208** [comment]
Manage to get the correct result by using something like "Eigen::Vector3d bar2 = T_cur_ref.so3().log();", so the output off foo.so3().log() seems to be the same as the first row of the SE3 object.

![log](https://user-images.githubusercontent.com/34848593/89473278-6513cd80-d77a-11ea-814d-7715568bd677.png)
