### ISSUE TITLE
What actually happens if I use a SE3 object to multiply an Eigen Vector3d object?

### ISSUE THREAD

**Issue by yrq0208** [strasdat/Sophus#252]
Hi all,

I wonder what actually happens if I use a SE3 object to multiply an Eigen Vector3d object? For example, we have

Sophus::SE3 foo;
Eigen::Vector3d bar;
Eigen::Vector3d result = foo * bar;

I think it is not simply matrix vector multiplication isn't it, otherwise the result should be a Vector2d rather than Vector3d. I fail to reproduce the correct result if I just treat it as simple matrix vector multiplication.

Thanks.

**Comment by NikolausDemmel** [comment]
It's rigid body transformation. I.e. if your SE3 transformation is represented by rotation matrix R and translation vector t, the result is equivalent to `result = R * foo + t`. In Sophus rotation is actually represented as quaternion, but the idea is the same.

I recommend you to read up on SO3 and SE3 to get a better understanding. Hauke's thesis has some good introductory material: https://www.doc.ic.ac.uk/~ajd/Publications/Strasdat-H-2012-PhD-Thesis.pdf
