### ISSUE TITLE
cmake problem

### ISSUE THREAD

**Issue by MyHubTo** [strasdat/Sophus#255]
hi ,guys,there are some problems when i camke my test project :

[main] Building folder: usesophus 
[main] Configuring folder: usesophus 
[main] Configuring folder: usesophus 
[cmake] Configuring done
[cmake] Generating done
[build] Starting build
[proc] Executing command: /usr/local/bin/cmake --build /home/mrzhao/Documents/Vscode/chapter3/usesophus/build --config Debug --target usesophus -- -j 10
[build] [ 50%] Building CXX object CMakeFiles/usesophus.dir/usesophus.cpp.o
[build] In file included from /usr/local/include/sophus/so3.hpp:8:0,
[build]                  from /usr/local/include/sophus/se3.hpp:7,
[build]                  from /home/mrzhao/Documents/Vscode/chapter3/usesophus/usesophus.cpp:17:
[build] /usr/local/include/sophus/so2.hpp:106:40: error: ‘ScalarBinaryOpTraits’ in namespace ‘Eigen’ does not name a template type
[build]    using ReturnScalar = typename Eigen::ScalarBinaryOpTraits<
[build]                                         ^
[build] /usr/local/include/sophus/so2.hpp:110:26: error: ‘ReturnScalar’ was not declared in this scope
[build]    using SO2Product = SO2<ReturnScalar<OtherDerived>>;
[build]                           ^
[build] /usr/local/include/sophus/so2.hpp:110:39: error: template argument 1 is invalid
[build]    using SO2Product = SO2<ReturnScalar<OtherDerived>>;
[build]                                        ^
[build] /usr/local/include/sophus/so2.hpp:113:32: error: ‘ReturnScalar’ was not declared in this scope
[build]    using PointProduct = Vector2<ReturnScalar<PointDerived>>;
[build]                                 ^
[build] /usr/local/include/sophus/so2.hpp:113:45: error: template argument 1 is invalid
[build]    using PointProduct = Vector2<ReturnScalar<PointDerived>>;
[build]                                              ^
[build] /usr/local/include/sophus/so2.hpp:116:43: error: ‘ReturnScalar’ was not declared in this scope
[build]    using HomogeneousPointProduct = Vector3<ReturnScalar<HPointDerived>>;
[build]                                            ^
[build] /usr/local/include/sophus/so2.hpp:116:56: error: template argument 1 is invalid
[build]    using HomogeneousPointProduct = Vector3<ReturnScalar<HPointDerived>>;
[build]                                                         ^
[build] /usr/local/include/sophus/so2.hpp:214:15: error: ‘SO2Product’ does not name a type
[build]    SOPHUS_FUNC SO2Product<OtherDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/so2.hpp:249:15: error: ‘PointProduct’ does not name a type
[build]    SOPHUS_FUNC PointProduct<PointDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/so2.hpp:265:15: error: ‘HomogeneousPointProduct’ does not name a type
[build]    SOPHUS_FUNC HomogeneousPointProduct<HPointDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/so2.hpp:289:38: error: ‘ReturnScalar’ was not declared in this scope
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                       ^
[build] /usr/local/include/sophus/so2.hpp:289:51: error: template argument 2 is invalid
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                    ^
[build] /usr/local/include/sophus/so2.hpp:289:63: error: template argument 1 is invalid
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                                ^
[build] /usr/local/include/sophus/so2.hpp:289:75: error: ‘type’ in namespace ‘::’ does not name a type
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                                            ^
[build] In file included from /usr/local/include/sophus/se3.hpp:7:0,
[build]                  from /home/mrzhao/Documents/Vscode/chapter3/usesophus/usesophus.cpp:17:
[build] /usr/local/include/sophus/so3.hpp:110:40: error: ‘ScalarBinaryOpTraits’ in namespace ‘Eigen’ does not name a template type
[build]    using ReturnScalar = typename Eigen::ScalarBinaryOpTraits<
[build]                                         ^
[build] /usr/local/include/sophus/so3.hpp:114:26: error: ‘ReturnScalar’ was not declared in this scope
[build]    using SO3Product = SO3<ReturnScalar<OtherDerived>>;
[build]                           ^
[build] /usr/local/include/sophus/so3.hpp:114:39: error: template argument 1 is invalid
[build]    using SO3Product = SO3<ReturnScalar<OtherDerived>>;
[build]                                        ^
[build] /usr/local/include/sophus/so3.hpp:117:32: error: ‘ReturnScalar’ was not declared in this scope
[build]    using PointProduct = Vector3<ReturnScalar<PointDerived>>;
[build]                                 ^
[build] /usr/local/include/sophus/so3.hpp:117:45: error: template argument 1 is invalid
[build]    using PointProduct = Vector3<ReturnScalar<PointDerived>>;
[build]                                              ^
[build] /usr/local/include/sophus/so3.hpp:120:43: error: ‘ReturnScalar’ was not declared in this scope
[build]    using HomogeneousPointProduct = Vector4<ReturnScalar<HPointDerived>>;
[build]                                            ^
[build] /usr/local/include/sophus/so3.hpp:120:56: error: template argument 1 is invalid
[build]    using HomogeneousPointProduct = Vector4<ReturnScalar<HPointDerived>>;
[build]                                                         ^
[build] /usr/local/include/sophus/so3.hpp:329:15: error: ‘SO3Product’ does not name a type
[build]    SOPHUS_FUNC SO3Product<OtherDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/so3.hpp:362:15: error: ‘PointProduct’ does not name a type
[build]    SOPHUS_FUNC PointProduct<PointDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/so3.hpp:377:15: error: ‘HomogeneousPointProduct’ does not name a type
[build]    SOPHUS_FUNC HomogeneousPointProduct<HPointDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/so3.hpp:399:38: error: ‘ReturnScalar’ was not declared in this scope
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                       ^
[build] /usr/local/include/sophus/so3.hpp:399:51: error: template argument 2 is invalid
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                    ^
[build] /usr/local/include/sophus/so3.hpp:399:63: error: template argument 1 is invalid
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                                ^
[build] /usr/local/include/sophus/so3.hpp:399:75: error: ‘type’ in namespace ‘::’ does not name a type
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                                            ^
[build] In file included from /home/mrzhao/Documents/Vscode/chapter3/usesophus/usesophus.cpp:17:0:
[build] /usr/local/include/sophus/se3.hpp:85:40: error: ‘ScalarBinaryOpTraits’ in namespace ‘Eigen’ does not name a template type
[build]    using ReturnScalar = typename Eigen::ScalarBinaryOpTraits<
[build]                                         ^
[build] /usr/local/include/sophus/se3.hpp:89:26: error: ‘ReturnScalar’ was not declared in this scope
[build]    using SE3Product = SE3<ReturnScalar<OtherDerived>>;
[build]                           ^
[build] /usr/local/include/sophus/se3.hpp:89:39: error: template argument 1 is invalid
[build]    using SE3Product = SE3<ReturnScalar<OtherDerived>>;
[build]                                        ^
[build] /usr/local/include/sophus/se3.hpp:92:32: error: ‘ReturnScalar’ was not declared in this scope
[build]    using PointProduct = Vector3<ReturnScalar<PointDerived>>;
[build]                                 ^
[build] /usr/local/include/sophus/se3.hpp:92:45: error: template argument 1 is invalid
[build]    using PointProduct = Vector3<ReturnScalar<PointDerived>>;
[build]                                              ^
[build] /usr/local/include/sophus/se3.hpp:95:43: error: ‘ReturnScalar’ was not declared in this scope
[build]    using HomogeneousPointProduct = Vector4<ReturnScalar<HPointDerived>>;
[build]                                            ^
[build] /usr/local/include/sophus/se3.hpp:95:56: error: template argument 1 is invalid
[build]    using HomogeneousPointProduct = Vector4<ReturnScalar<HPointDerived>>;
[build]                                                         ^
[build] /usr/local/include/sophus/se3.hpp:308:15: error: ‘SE3Product’ does not name a type
[build]    SOPHUS_FUNC SE3Product<OtherDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/se3.hpp:325:15: error: ‘PointProduct’ does not name a type
[build]    SOPHUS_FUNC PointProduct<PointDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/se3.hpp:335:15: error: ‘HomogeneousPointProduct’ does not name a type
[build]    SOPHUS_FUNC HomogeneousPointProduct<HPointDerived> operator*(
[build]                ^
[build] /usr/local/include/sophus/se3.hpp:359:38: error: ‘ReturnScalar’ was not declared in this scope
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                       ^
[build] /usr/local/include/sophus/se3.hpp:359:51: error: template argument 2 is invalid
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                    ^
[build] /usr/local/include/sophus/se3.hpp:359:63: error: template argument 1 is invalid
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                                ^
[build] /usr/local/include/sophus/se3.hpp:359:75: error: ‘type’ in namespace ‘::’ does not name a type
[build]                  std::is_same<Scalar, ReturnScalar<OtherDerived>>::value>::type>
[build]                                                                            ^
[build] CMakeFiles/usesophus.dir/build.make:62: recipe for target 'CMakeFiles/usesophus.dir/usesophus.cpp.o' failed
[build] CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/usesophus.dir/all' failed
[build] CMakeFiles/Makefile2:79: recipe for target 'CMakeFiles/usesophus.dir/rule' failed
[build] Makefile:118: recipe for target 'usesophus' failed
[build] make[3]: *** [CMakeFiles/usesophus.dir/usesophus.cpp.o] Error 1
[build] make[2]: *** [CMakeFiles/usesophus.dir/all] Error 2
[build] make[1]: *** [CMakeFiles/usesophus.dir/rule] Error 2
[build] make: *** [usesophus] Error 2
[build] Build finished with exit code 2

so,what can i do?

**Comment by sergiud** [comment]
You seem to be using a build system on top of CMake which probably interferes with the latter.

**Comment by YonatanSimson** [comment]
Try replacing in CMakeLists.txt:
`include_directories( "/usr/include/eigen3" )`
with
`include_directories( "/usr/local/include/eigen3" )`

**Comment by strasdat** [comment]
Let's use the community Q&A forum for these type of discussions in the future: https://github.com/strasdat/Sophus/discussions/categories/q-a
