### ISSUE TITLE
Using Sophus::SE3f with std::vector

### ISSUE THREAD

**Issue by lanfeiying** [strasdat/Sophus#256]
Hi,
I have a question about using `Sophus::SE3f` with `std::vector`.

If I have a class like this:
```
class MyClass
{
    //Should I add this macro from Eigen?
//    EIGEN_MAKE_ALIGNED_OPERATOR_NEW

public:
    /*methods*/
    ....

private:
    //Is it correct?
    std::vector<Sophus::SE3f> se3_list;
};
```
In `MyClass`, it contains an std container `std::vector<Sophus::SE3f>`. Does it have memory alignment issues? 

I checked the documentation, both of `SE3f` and `SO3f` have `Eigen::Quaternion` as its member variable. 

According to Eigen's documentation, `MyClass` should have `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` macro for memory alignment, 
see [here](https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html).

For using `std::vector`, it should use `Eigen::aligned_allocator<Eigen::Type>`, 
see [here](https://eigen.tuxfamily.org/dox/group__TopicStlContainers.html) .
```
std::vector<Eigen::Matrix4f, Eigen::aligned_allocator<Eigen::Matrix4f>> my_matrix_vec;
```

**Question 1**
I didn't found `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` in `Sophus::SE3f` source code, 
[here](https://strasdat.github.io/Sophus/class_Sophus_SE3.html#doxid-class-sophus-1-1-s-e3) .
How does libsophus deal with this memory alignment problem?

So, in my case, should I add `EIGEN_MAKE_ALIGNED_OPERATOR_NEW` in `MyClass`?

**Question 2**
If I use `std::vector<Sophus::SE3f>`, should I add Eigen allocator? 
Does it have memory alignment issues?

**Comment by NikolausDemmel** [comment]
> I didn't found EIGEN_MAKE_ALIGNED_OPERATOR_NEW in Sophus::SE3f source code

It's there: https://github.com/strasdat/Sophus/blob/593db47500ea1a2de5f0e6579c86147991509c59/sophus/se3.hpp#L446

> So, in my case, should I add EIGEN_MAKE_ALIGNED_OPERATOR_NEW in MyClass?

No, you don't need alligned allocation for a class that contains a `std::vector` of obejcts with alignment. std::vector allocates it's own memory.

> If I use std::vector<Sophus::SE3f>, should I add Eigen allocator?

Yes, the same logic should apply as if you had e.g. `std::vector<Eigen::Vec4f>`. Note that if you are using C++17 you might be able to forget about this completely. And if you are using C++11 or C++14, things are also easier. See this devel-branch documentation: https://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html

**Comment by lanfeiying** [comment]
> > I didn't found EIGEN_MAKE_ALIGNED_OPERATOR_NEW in Sophus::SE3f source code
> 
> It's there:
> 
> https://github.com/strasdat/Sophus/blob/593db47500ea1a2de5f0e6579c86147991509c59/sophus/se3.hpp#L446
> 
> > So, in my case, should I add EIGEN_MAKE_ALIGNED_OPERATOR_NEW in MyClass?
> 
> No, you don't need alligned allocation for a class that contains a `std::vector` of obejcts with alignment. std::vector allocates it's own memory.
> 
> > If I use std::vectorSophus::SE3f, should I add Eigen allocator?
> 
> Yes, the same logic should apply as if you had e.g. `std::vector<Eigen::Vec4f>`. Note that if you are using C++17 you might be able to forget about this completely. And if you are using C++11 or C++14, things are also easier. See this devel-branch documentation: https://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html

Thank you very much! 
For question 2, should I use Eigen's allocator like following? 
```
std::vector<Sophus::SE3f, Eigen::aligned_allocator<Sophus::SE3f>>
```

**Comment by NikolausDemmel** [comment]
> For question 2, should I use Eigen's allocator like following?

Yes, for C++11 and C++14. For C++17 and newer you can skip the allocator alltogether. At least that is how I interpret the Eigen docs.

**Comment by lanfeiying** [comment]
Thank you very much!
