### ISSUE TITLE
Can't use as a subdirectory in a CMake project

### ISSUE THREAD

**Issue by sotpapathe** [strasdat/Sophus#257]
When putting Sophus in a subdirectory of another CMake project (either copied or as a git submodule), the header files can't be found by CMake.

For the following minimal example

``` text
├── CMakeLists.txt
├── main.cpp
└── Sophus
    └── ...
```

with `CMakeLists.txt`

``` cmake
cmake_minimum_required(VERSION 3.4)
project(SophusTest VERSION 0.1.0)

add_subdirectory(Sophus)

find_package(Sophus 1.0 REQUIRED)

add_executable(exe main.cpp)
target_link_libraries(exe Sophus::Sophus)
```

compilation results in a header not found error.

The minimal example: [sophus_as_subdirectory.zip](https://github.com/strasdat/Sophus/files/5283511/sophus_as_subdirectory.zip)

**Comment by sergiud** [comment]
This is not how CMake works. `find_package` use is orthogonal to including projects via `add_subdirectory`.

What are you trying to achieve in the first place?

**Comment by sotpapathe** [comment]
> This is not how CMake works. find_package use is orthogonal to including projects via add_subdirectory.

My bad, wasn't aware of this. I've seen what I tried being recommended in more that one CMake tutorial. The following works with commit Sophus 488f5fa:

``` cmake
cmake_minimum_required(VERSION 3.4)
project(SophusTest VERSION 0.1.0)

add_subdirectory(Sophus)

add_executable(exe main.cpp)
target_link_libraries(exe PRIVATE sophus)
```

Thanks!
