### ISSUE TITLE
invalid use of template-name ‘Sophus::SE3’ without an argument list

### ISSUE THREAD

**Issue by gregsensem** [strasdat/Sophus#258]
hi guys, I encountered this error when do make after cmake. do you have any idea what caused this? thanks!!

error: invalid use of template-name ‘Sophus::SE3’ without an argument list
   33 | Sophus::SE3 transT_cv2sophus(const cv::Mat &T_cv);

**Comment by zeroflycui** [comment]
maybe the sophus you are using came with a template .when you declare a variable you must like this Sophus::SE3<type> name or Sophus::SE3d name.

**Comment by strasdat** [comment]
Possibly a very old version of Sophus...
