### ISSUE TITLE
Is there any need to include trace differentiation on SO(3)?

### ISSUE THREAD

**Issue by zarathustr** [strasdat/Sophus#262]
Hi guys, there are some demands on online differentiation on SO(3) for optimization problems. However, many of these optimization objectives are scalar, e.g. in the way of matrix trace operation. However, I do not see such operation in the current Sophus lib. One may get an approximate Jacobian by first-order Taylor expansion. But this actually does not act as a proper choice dealing with many globally optimal estimates. Therefore I wonder if this can be merged into the mainstream of Sophus? Thanks!

**Comment by strasdat** [comment]
Sure. Go ahead and create a PR ;)
