### ISSUE TITLE
Memory alignment issues using Sophus::SE3f as a member variable in a class

### ISSUE THREAD

**Issue by lanfeiying** [strasdat/Sophus#264]
Hi,
I encountered a problem when I was using Sophus::SE3f in my code. There is a class defined in my code:
```
class MyClass
{
public:
    MyClass();
    /*other member functions*/

private:
    float3 member_var;
    Sophus::SE3f pose;
    int id;
    /*......*/
};
```

As the code is shown above, if `pose` is not the first member variable in `MyClass`, e.g. after `float3 member_var`, the program got `segmentation fault ( core dumped)` error. 

If I put `Sophus::SE3f pose` as the first member variable, there is no segfault error. 

I checked the documentation of Eigen library about memory alignment issues, see [here](https://eigen.tuxfamily.org/dox/group__TopicStructHavingEigenMembers.html).
It says that Eigen member variables are not required to be put at the beginning of the class.

I am wondering whether it is a bug from Eigen or my code?

**Comment by strasdat** [comment]
Over two years old...
