### ISSUE TITLE
Program can not find Sophus

### ISSUE THREAD

**Issue by ghost** [strasdat/Sophus#268]
Hi I have download Sophus, built it and install it with 

`sudo make install`

However, when my program was trying to use it, I got the following error:

fatal error: sophus/so3.h: No such file or directory 

Why?

**Comment by sergiud** [comment]
It would help if you provide the command line you used for all the steps and the corresponding output. Otherwise, one must assume your setup is incorrect.

**Comment by Jiajie-Shi** [comment]
try use 
`#include <sophus/so3.hpp>`
and check your directory /usr/local/include/sophus whether have so3.hpp or not.
I have got this error before and I did the above way.

**Comment by YonatanSimson** [comment]
`#include <sophus/so3.hpp>` 
fixed the problem for me
