### ISSUE TITLE
Sophus fails to build on OSX

### ISSUE THREAD

**Issue by kubark42** [strasdat/Sophus#27]
As per https://github.com/uzh-rpg/rpg_svo/issues/16#issuecomment-58793466, Sophus fails to compile on OSX. A solution which works is to replace (in sophus/so2.cpp):

```
unit_complex_.real() = 1.; 
unit_complex_.imag() = 0.;
```
with:

```unit_complex_ = Complexd(1.,0.);```

**Comment by strasdat** [comment]
Thanks for reporting. I hope I will find time in the next couple of weeks to add OSX to travis CI.

**Comment by strasdat** [comment]
Builds ok on OSX: https://travis-ci.org/strasdat/Sophus/builds/165377746
