### ISSUE TITLE
Cant Find Sophus::leftJacobianInvSO3()

### ISSUE THREAD

**Issue by YangSiri** [strasdat/Sophus#273]
Hi, contributorst 

I build the standard Sophus lib and make_installed in my self-defined folder. Everything goes fine but function __Sophus::leftJacobianInvSO3()__ doesnt exist and I cant find it anywhere. Could you please tell me if this function is in Sophus?

Looking forward to your help :)

**Comment by NikolausDemmel** [comment]
I think you are looking for this, in a different project, **basalt-headers**: https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/master/include/basalt/utils/sophus_utils.hpp

PS: It's debatable whether putting it in the Sophus namespace was the right choice, but there it is :man_shrugging:.

**Comment by YangSiri** [comment]
Lol, @NikolausDemmel 

Thank you very much~

**Comment by YangSiri** [comment]
Hi, @NikolausDemmel 

Sorry to interrupt youu again. I'm noticed that you are also one of the contributor of __SE3Spline__ in the basalt headers which is a great work. Recently I've conducted some tests to adopt the __Jacobian__ evaluation in it, but i'm a little confused by the data structure. 

In a word, I want to withdraw the __Jacobian__ with reference to different knots which is in _Sophus::SE3d pose(int64_t time_ns, PosePosSO3JacobianStruct *J) const{}_ function. To do this, I generate a random spline and individually perturbate every parameters in the SE3.data() to see the corresponding derivatives. But the results seem to be inconsistent. I wonder where did i make some mistakes. 

`basalt::Se3Spline<4> se3Spline = basalt::Se3Spline<4>(100);
    se3Spline.genRandomTrajectory(5);
    int64_t maxT = se3Spline.maxTimeNs();
    cout << "[ DEBUG ] maxTimeNs : " << maxT << endl;
    cout << GREEN << setprecision(7) ;
    se3Spline.print_knots();
    cout << RESET;
    double* params[5];
//    double* trans[5];
    cout << " Copying Parameters ..." << endl;
    for (int i = 0; i < 5; ++i){
        params[i] = new double[7];
        memcpy(params[i], se3Spline.getKnot(i).data(), 7* sizeof(double ));
//        params[i] = se3Spline.getKnot(i).data();
        for (int j = 0; j < 7; ++j) cout << params[i][j] << " " ;
        cout << endl;
    }

    cout << "==================== Evaluating Sophus Spline Jacobians ================================" << endl;
    Sophus::SE3<double> T_ori, T_aft;
    basalt::Se3Spline<4>::PosePosSO3JacobianStruct JacobsSpline;
    T_ori = se3Spline.pose(maxT * 0.3);
    cout << YELLOW << "[ JacobTest ] Pose.log() before : " << T_ori.log().transpose() << RESET << endl;

    for (int i = 0; i < 5; ++i) {

//        Sophus::SO3<double> rot = se3Spline.getKnotSO3(i);
//        Eigen::Vector3d rot_log = rot.log();
        Eigen::Map<Eigen::Quaternion<double> > quat (se3Spline.getKnotSO3(i).data());
        for (int j = 0; j < 7; ++j) {

            cout << "[ JacobTest ] Perturbation in  " << CYAN << i << ", " << j << RESET;
            cout << " Original Value " << params[i][j];
            params[i][j] += 1e-6;
            cout << " with new value " << params[i][j] << endl;

//            cout << " Original rot Value " << rot_log.transpose();
//            rot_log(j) += 1e-6;
//            cout << " with new rot value " << rot_log.transpose() << endl;
//            rot = Sophus::SO3<double>::exp(rot_log);
//            se3Spline.getKnotSO3(i) = rot;
            if (j>3)
                se3Spline.getKnotPos(i) = Eigen::Map<Eigen::Vector3d>(params[i] + 4);
            else
                quat = Eigen::Map<Eigen::Quaternion<double> >(params[i]);

            cout << GREEN;
            se3Spline.print_knots();
            cout << RESET;

            T_aft = se3Spline.pose(maxT * 0.3, &JacobsSpline);
            cout << "[ JacobTest ] Pose.log() after : " << T_aft.log().transpose() << endl;

            cout << RED << "[ JacobTest ] Numeric : " << (T_aft.log() - T_ori.log()).transpose() / 1e-6
                 << " ，Analytic : \n" << JacobsSpline.d_val_d_knot[i].matrix() << RESET << endl;
            params[i][j] -= 1e-6;
//            rot_log(j) -= 1e-6;
            if(j == 3)
                quat = Eigen::Map<Eigen::Quaternion<double> >(params[i]);
        }
//        rot = Sophus::SO3<double>::exp(rot_log);
//        se3Spline.getKnotSO3(i) = rot;
        // recover
        se3Spline.getKnotPos(i) = Eigen::Map<Eigen::Vector3d>(params[i] + 4);
    }`

Looking forward to your generous help ;)

**Comment by NikolausDemmel** [comment]
There is already a numeric differentiation unit test for this I believe: https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/4b62bcbdb343cc9464ba1de800ddcfd9942a9a6f/test/src/test_spline_se3.cpp#L254

You can have a look there to see what is different.

Further questions should be asked on the basalt headers repository though.

**Comment by YangSiri** [comment]
Thank you very much, @NikolausDemmel 

I would look into it and check my mistakes.
