### ISSUE TITLE
make install error

### ISSUE THREAD

**Issue by Jowisdom** [strasdat/Sophus#292]
CMake Error at cmake_install.cmake:69 (file):
  file INSTALL cannot find
.../Sophus/sophus/formatstring.hpp": No such file or directory.

**Comment by strasdat** [comment]
To fix it, remove the formatstring.hpp entry from the top-level cmake file.

**Comment by strasdat** [comment]
This should fix it:

https://github.com/strasdat/Sophus/pull/297
