### ISSUE TITLE
SE3 translation error

### ISSUE THREAD

**Issue by franciscodominguezmateos** [strasdat/Sophus#30]
Hello this code 
	cout << "d" <<d.matrix() <<endl;
	Tangent td=SE3Type::log(d);
	SE3Type de=SE3Type::exp(td);
	cout << "de"<< de.matrix() <<endl;
output this:
d  0.904771   0.411846   0.108502   -3.01266
  0.138871 -0.0444436  -0.989313    2.20879
 -0.402622   0.910169 -0.0974046    1.42016
         0          0          0          1
de  0.904771   0.411846   0.108502    -3.3656
  0.138871 -0.0444436  -0.989313    3.29317
 -0.402622   0.910169 -0.0974046    1.42016
         0          0          0          1
I think d and d3 must be equals, but the translations tx and ty are differrents.
I try to interpolate two poses and starting in the right position p0 don't interpolate the final position p1.
This is a implementation of the method:
SE3Type interpolation(SE3Type &a,SE3Type &b, Escalar t){
	cout << "t"<< t<<endl;
	SE3Type d=b*a.inverse();
	cout << "d" <<d.matrix() <<endl;
	Tangent td=SE3Type::log(d);
	SE3Type de=SE3Type::exp(td);
	cout << "de"<< de.matrix() <<endl;
	Tangent dt=td*t;
	SE3Type ret=SE3Type::exp(dt)*a;
	return ret;
}
I thinks it is a bug of sophus. Doesn't it?
Thanks in advance.
 Paco

**Comment by strasdat** [comment]
This should be covered by the unit tests (i.e. ``expLogTest``). Are the tests failing for you?

Also, could you provide a complete minimal example; especially what it ``d``? Thanks.

**Comment by franciscodominguezmateos** [comment]
Yes and I have made the same with other library from Ethan Eade and everything works perfectly.
The examples is in the first post, all you need is the value of d, it is:
SE3Type d(Quaternion<double>(-0.3909,0.8851,0.2362,-0.0898),Punto(1.3112,0.8507,-1.5186));
May be it is a problem with Eigen library. When I compile your last code I find this error:
.........................................
/home/francisco/git/Sophus/sophus/se3.hpp: In static member function ‘static void Sophus::SE3GroupBase<Derived>::internalGenerator(int, Eigen::Quaternion<typename Eigen::internal::traits<T>::Scalar>*, Eigen::Matrix<typename Eigen::internal::traits<T>::Scalar, 3, 1>*)’:
/home/francisco/git/Sophus/sophus/ensure.hpp:72:25: error: ‘defaultEnsure’ is not a member of ‘Sophus’
   ((expr) ? ((void)0) : Sophus::defaultEnsure(SOPHUS_FUNCTION, __FILE__, \
                         ^
/home/francisco/git/Sophus/sophus/se3.hpp:519:5: note: in expansion of macro ‘SOPHUS_ENSURE’
     SOPHUS_ENSURE(i >= 0 && i <= 5, "i should be in range [0,5]");
     ^
/home/francisco/git/Sophus/sophus/ensure.hpp:72:25: error: ‘defaultEnsure’ is not a member of ‘Sophus’
   ((expr) ? ((void)0) : Sophus::defaultEnsure(SOPHUS_FUNCTION, __FILE__, \
                         ^
/home/francisco/git/Sophus/sophus/se3.hpp:520:5: note: in expansion of macro ‘SOPHUS_ENSURE’
     SOPHUS_ENSURE(internal_gen_q != NULL,
     ^
/home/francisco/git/Sophus/sophus/ensure.hpp:72:25: error: ‘defaultEnsure’ is not a member of ‘Sophus’
   ((expr) ? ((void)0) : Sophus::defaultEnsure(SOPHUS_FUNCTION, __FILE__, \
                         ^
/home/francisco/git/Sophus/sophus/se3.hpp:522:5: note: in expansion of macro ‘SOPHUS_ENSURE’
     SOPHUS_ENSURE(internal_gen_t != NULL,
     ^
make[2]: *** [test/ceres/CMakeFiles/test_ceres_se3.dir/test_ceres_se3.cpp.o] Error 1
make[2]: Leaving directory `/home/francisco/git/Sophus/build'
make[1]: *** [test/ceres/CMakeFiles/test_ceres_se3.dir/all] Error 2
make[1]: Leaving directory `/home/francisco/git/Sophus/build'
make: *** [all] Error 2

It is very weird, I am developing a sophus version in python, and I got stuck with this problem.

**Comment by strasdat** [comment]
I tried it out:

```
  SE3Type pose1(Eigen::Quaternion<Scalar>(-0.3909, 0.8851, 0.2362, -0.0898), 
	            Point(1.3112, 0.8507, -1.5186));
  std::cerr << "pose1:" << pose1.matrix() << std::endl;
  SE3Type pose2 = SE3Type::exp(SE3Type::log(pose1));
  std::cerr << "pose2:" << pose2.matrix() << std::endl;
  std::cerr << "pose1-pose2:" << pose1.matrix() - pose1.matrix() << std::endl;
```

I'm getting sane results:

```
pose1:
 0.872299  0.347895 -0.343605    1.3112
 0.488298 -0.582839  0.649511    0.8507
0.0256957 -0.734349 -0.678286   -1.5186
        0         0         0         1
pose2:
 0.872299  0.347895 -0.343605    1.3112
 0.488298 -0.582838  0.649511    0.8507
0.0256957 -0.734349 -0.678285   -1.5186
        0         0         0         1
pose1-pose2:
0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0
```

Not sure what's wrong on your side, but I doubt it is an issue with Sophus.

**Comment by franciscodominguezmateos** [comment]
Thanks you.
Sure it is not Sophus.
On the other hand I have just tried Sophus in other machine, with 
eclipse but I get errors too, this time one differente I have opened a 
issue. I use Sophus as Eigen only including. Is that right?
Thanks again.
  Paco

**Comment by franciscodominguezmateos** [comment]
Hello
Same code I get this:
pose1: 0.872299  0.347895 -0.343605    1.3112
 0.488298 -0.582838  0.649511    0.8507
0.0256957 -0.734349 -0.678285   -1.5186
        0         0         0         1
pose2: 0.872299  0.347895 -0.343605  0.993399
 0.488298 -0.582838  0.649511   2.16017
0.0256957 -0.734349 -0.678285   -1.5186
        0         0         0         1
pose1-pose2:0 0 0 0
0 0 0 0
0 0 0 0
0 0 0 0
Any idea?
As you see the difference is 0!! but the printing are different!!!
Thank you.
 Paco

**Comment by franciscodominguezmateos** [comment]
I have just done pull and It compiles fine. The ceres compilation problem as gone. The test_se3 works fine, but my example fail as before. I will try to compile with cmake, I am compiling with eclipse and including sophus/se3.hpp.

**Comment by franciscodominguezmateos** [comment]
I have just tried with cmake and same problem. Print different matrix but give 0 as difference. I like you lib very much but I am going to be forced to give it up. It is a pity.
