### ISSUE TITLE
Get roll/pitch/yaw from SE3

### ISSUE THREAD

**Issue by ghost** [strasdat/Sophus#309]
How can I get the euler angles from SE3?

**Comment by DmitriyKorchemkin** [comment]
1. Get unit quaternion using se3.so3().unit_quaternion()
2. Convert it to Euler (or Tait-Bryan) angles using Eigen::EulerAngles ( https://eigen.tuxfamily.org/dox/unsupported/classEigen_1_1EulerAngles.html )

**Comment by libdoron** [comment]
> 1. Get unit quaternion using se3.so3().unit_quaternion()
> 2. Convert it to Euler (or Tait-Bryan) angles using Eigen::EulerAngles ( https://eigen.tuxfamily.org/dox/unsupported/classEigen_1_1EulerAngles.html )

I try to get the roll/pitch/yaw from SE3.
Can someone please explain the totally different values I get while using those 3 methods?
1. Using the Quaternion, the way it is described here.
2. using the 'angleX()', 'angleY()' and 'angleZ()' functions?
3. Extracting euler angles from 'rotationMatrix()' ( an implementation can be found [here](https://learnopencv.com/rotation-matrix-to-euler-angles/) )

(This is a much shorter description, but still a duplication of #519 )
