### ISSUE TITLE
FMT is required?

### ISSUE THREAD

**Issue by Smithangshu** [strasdat/Sophus#321]
Hi,

According to the documentation, FMT is optional library but when building with CMAKE with Use_Basic_Logging flag true, I can see common.hpp is still looking for FMT headers. I can not use Sophus without FMT. Is it really possible to use Sophus without FMT?

**Comment by xingruiy** [comment]
Hi,

I am having the same problem here. I have to add `add_definitions("-D SOPHUS_USE_BASIC_LOGGING")` to my CMake project as a workaround. I noticed this change has been introduced recently, is this an intended behaviour?

**Comment by sergiud** [comment]
`SOPHUS_USE_BASIC_LOGGING` is already defined by Sophus:
https://github.com/strasdat/Sophus/blob/49a7e1286910019f74fb4f0bb3e213c909f8e1b7/CMakeLists.txt#L91
No need to define it yourself. It's more likely that you omit the `Sophus::Sophus` import target which propagates the correct definitions and dependencies.

**Comment by Shubham-2302** [comment]
Hey @Smithangshu I am trying to build minisam too. Can you elaborate what fix worked for you to get by the fmt issue?
PS: i am not experienced with Cmake
