### ISSUE TITLE
 error: ‘ceres::isfinite’ has not been declared

### ISSUE THREAD

**Issue by yinwu33** [strasdat/Sophus#326]
Hello, I met the compiling problem of Sophus, which shows the ` error: ‘ceres::isfinite’ has not been declared`. Can anyone help me?

**Comment by NikolausDemmel** [comment]
I guess there is a typo here: https://github.com/strasdat/Sophus/blob/d869310c066df26f9afe4071d4ebac6c0d007073/test/core/tests.hpp#L22

Can you try replacing that line with 

```
#ifdef SOPHUS_CERES`
```

?

**Comment by NikolausDemmel** [comment]
Ah wait, that might not be it. It was just a guess, but there are more `#if SOPHUS_CERES` in other places.

**Comment by yinwu33** [comment]
> mmand line output (for a fresh build fol

I compile the Sophus of the latest version in Ubuntu 20.04, g++-9. I actually consider that I made some problem with the installation of ceres and eigen. But I have tried to reinstall the two lib several times and not fixed yet.

```
ubuntu@ubuntu-PC:~/Documents/Sophus/build git:(master) 1M $ make
[  7%] Built target test_common
Scanning dependencies of target test_so2
[ 10%] Building CXX object test/core/CMakeFiles/test_so2.dir/test_so2.cpp.o
In file included from /home/ubuntu/Documents/Sophus/test/core/test_so2.cpp:4:
/home/ubuntu/Documents/Sophus/test/core/tests.hpp:23:14: error: ‘ceres::isfinite’ has not been declared
   23 | using ceres::isfinite;
      |              ^~~~~~~~
make[2]: *** [test/core/CMakeFiles/test_so2.dir/build.make:63: test/core/CMakeFiles/test_so2.dir/test_so2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:231: test/core/CMakeFiles/test_so2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
```

**Comment by NikolausDemmel** [comment]
If it's compiling that line `using ceres::isfinite;`, I guess cmake did find Ceres (you didn't show the cmake output so I cannot verify), so it must also use the `#include <ceres/jet.h>`. The only reason I can think of is that it somehow finds a very old version of the ceres header on your machine, which doesn't have the `isfinite` function defined. In version 2.0 of Ceres, which Sophus expects, this should be defined in `jet.h`. Looks like it was added more than 3 years ago in Ceres: https://github.com/ceres-solver/ceres-solver/commit/31f24521ccc3c480ae4dbea403af4526069b3e7c

**Comment by NikolausDemmel** [comment]
PS: Ceres here is only used optionally for unit tests, so if you just wanna use Sophus in another project, you can just comment out the `find_package( Ceres ...)` in Sophus' CMakeLists.txt files and move on.

**Comment by yinwu33** [comment]
> If it's compiling that line `using ceres::isfinite;`, I guess cmake did find Ceres (you didn't show the cmake output so I cannot verify), so it must also use the `#include <ceres/jet.h>`. The only reason I can think of is that it somehow finds a very old version of the ceres header on your machine, which doesn't have the `isfinite` function defined. In version 2.0 of Ceres, which Sophus expects, this should be defined in `jet.h`. Looks like it was added more than 3 years ago in Ceres: [ceres-solver/ceres-solver@31f2452](https://github.com/ceres-solver/ceres-solver/commit/31f24521ccc3c480ae4dbea403af4526069b3e7c)

sorry, here is the output of cmake. And it show the ceres is found.

And yeh, maybe it's due to the version conflict, or maybe I haven't uninstalled the old ceres clearly. I'll check the `jet.h` file to make sure.

```
Turning basic logging ON
-- CERES found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/Documents/Sophus/build
```

**Comment by NikolausDemmel** [comment]
Ah true, the cmake output doesn't show which version it found. You can modify Sophus' CMakeLists.txt files and remove the `QUIET` from the `find_package( Ceres ... )` calls, then you should see output like this from cmake (at least if it does indeed find a recent version of Ceres; not sure if the output is the same for very old versions of Ceres):

```
-- Found required Ceres dependency: Eigen version 3.4.0 in /usr/local/include/eigen3
-- Found required Ceres dependency: glog
-- Found required Ceres dependency: gflags
-- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, AccelerateSparse, SchurSpecializations, Multithreading]
-- CERES found
```

If this shows the wrong version, you have your culprit (I'm not sure how `find_package( Ceres 2.0.0 )` behaves without `EXACT` or `REQUIRED`, if it finds a version older than 2.0.0).

If this shows the correct version (version 2.0), then it might be you have `jet.h` from an older version somewhere on the include path (`/usr/include/ceres/jet.h` or `/usr/local/include/ceres/jet.h`). One way to find out which file exactly is included by the compiler is the following.

1. Compile with make until you hit the compilation error.
2. Rerun make with verbose output `make VERBOSE=1`.
3. Identify the compiler command and manually rerun it in the terminal with an added `-H` command line flag. This should print a list of ALL include files that got included. In that list you can then identify which jet.h exactly is being included.

E.g., for me the command in the last step looks something like this, but yours will be different of course: 
 
```
cd /Users/demmeln/work/slam/Sophus/build/test/core && /usr/local/opt/ccache/libexec/c++ -DFMT_HEADER_ONLY=1 -DGFLAGS_IS_A_DLL=0 -DSOPHUS_CERES -I/Users/demmeln/work/slam/Sophus -isystem /usr/local/include/eigen3 -isystem /usr/local/include -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -std=gnu++14 -MD -MT test/core/CMakeFiles/test_velocities.dir/test_velocities.cpp.o -MF CMakeFiles/test_velocities.dir/test_velocities.cpp.o.d -c /Users/demmeln/work/slam/Sophus/test/core/test_velocities.cpp -H
```

**Comment by yinwu33** [comment]
> Ah true, the cmake output doesn't show which version it found. You can modify Sophus' CMakeLists.txt files and remove the `QUIET` from the `find_package( Ceres ... )` calls, then you should see output like this from cmake (at least if it does indeed find a recent version of Ceres; not sure if the output is the same for very old versions of Ceres):
> 
> ```
> -- Found required Ceres dependency: Eigen version 3.4.0 in /usr/local/include/eigen3
> -- Found required Ceres dependency: glog
> -- Found required Ceres dependency: gflags
> -- Found Ceres version: 2.0.0 installed in: /usr/local with components: [EigenSparse, SparseLinearAlgebraLibrary, LAPACK, SuiteSparse, CXSparse, AccelerateSparse, SchurSpecializations, Multithreading]
> -- CERES found
> ```
> 
> If this shows the wrong version, you have your culprit (I'm not sure how `find_package( Ceres 2.0.0 )` behaves without `EXACT` or `REQUIRED`, if it finds a version older than 2.0.0).
> 
> If this shows the correct version (version 2.0), then it might be you have `jet.h` from an older version somewhere on the include path (`/usr/include/ceres/jet.h` or `/usr/local/include/ceres/jet.h`). One way to find out which file exactly is included by the compiler is the following.
> 
> 1. Compile with make until you hit the compilation error.
> 2. Rerun make with verbose output `make VERBOSE=1`.
> 3. Identify the compiler command and manually rerun it in the terminal with an added `-H` command line flag. This should print a list of ALL include files that got included. In that list you can then identify which jet.h exactly is being included.
> 
> E.g., for me the command in the last step looks something like this, but yours will be different of course:
> 
> ```
> cd /Users/demmeln/work/slam/Sophus/build/test/core && /usr/local/opt/ccache/libexec/c++ -DFMT_HEADER_ONLY=1 -DGFLAGS_IS_A_DLL=0 -DSOPHUS_CERES -I/Users/demmeln/work/slam/Sophus -isystem /usr/local/include/eigen3 -isystem /usr/local/include -O3 -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.15 -std=gnu++14 -MD -MT test/core/CMakeFiles/test_velocities.dir/test_velocities.cpp.o -MF CMakeFiles/test_velocities.dir/test_velocities.cpp.o.d -c /Users/demmeln/work/slam/Sophus/test/core/test_velocities.cpp -H
> ```

Thank you very much! I finally solve the problem with your hints by checking files one by one. It's a really stupid problem, where there is an old project with an old ceres version, and somehow the `.bashrc` file was modified to use the old version ceres. That's the reason whatever I did with source file install or apt install, they all don't works.
