### ISSUE TITLE
ERROR When I used local_parameterization_se3.hpp

### ISSUE THREAD

**Issue by jsz0913** [strasdat/Sophus#329]
Hello,
error: static assertion failed: YOU_MIXED_MATRICES_OF_DIFFERENT_SIZES
   EIGEN_STATIC_ASSERT_SAME_MATRIX_SIZE(ActualDstTypeCleaned,Src)

actullay , i changed nothing about the code
could you help me?thx

**Comment by jsz0913** [comment]
This problem is probably due to version incompatibility

**Comment by MartinEekGerhardsen** [comment]
I'm having the same issue, did you figure out which versions should be used together?
