### ISSUE TITLE
error：compiled with VS2015 win64

### ISSUE THREAD

**Issue by nuli0355** [strasdat/Sophus#33]
I use Cmake3.5 and VS2015 on win8.1,but there is a error:
\sophus\sophus\ensure.hpp(60): error C2144: Syntax error: "void" should be preceded by ";"
\sophus\sophus\ensure.hpp(60): error C4430
thanks!
![error](https://cloud.githubusercontent.com/assets/15178973/19258784/db40a1ea-8fad-11e6-837d-41072ee5a38d.png)

**Comment by strasdat** [comment]
Interesting; it compiles fine on [CI](https://ci.appveyor.com/project/strasdat/sophus/build/1.0.42) using Visual Studio 14 2015 Win64.

**Comment by jlblancoc** [comment]
Could you try including at the top of that file the Eigen header that
defines the macro underlined?
Also, what version of Eigen did you tried out?

**Comment by strasdat** [comment]
I just merged a change, which I think fixes the issue. Please reopen, if this is not the case.
