### ISSUE TITLE
basic logging is unusable

### ISSUE THREAD

**Issue by sergiud** [strasdat/Sophus#331]
I noticed that Sophus output is not usable anymore with `USE_BASIC_LOGGING=ON`. Once basic logging is enabled, none of the `fmt` specific placeholders (e.g., `{}`) are actually substituted by the corresponding values.

I believe, the best course of action is therefore to remove basic logging altogether and make `fmt` a required dependency.

**Comment by strasdat** [comment]
At the moment I would like to support users who don't want to depend on fmt. The basic logging is not unusable but carries indeed less debug information.
