### ISSUE TITLE
`LocalParameterization` has been deprecated

### ISSUE THREAD

**Issue by sergiud** [strasdat/Sophus#334]
The upcoming Ceres solver 2.1 release [deprecates](https://github.com/ceres-solver/ceres-solver/blob/e0fef6ef05c580c40d6293749d8f88904d140c8d/include/ceres/local_parameterization.h#L117-L120) the `LocalParameterization` interface by replacing it by `Manifold`. The former will be removed in a subsequent release. The Ceres integration should therefore be updated to use the new interface.

**Comment by DmitriyKorchemkin** [comment]
I actually planned to update https://github.com/strasdat/Sophus/pull/305 by the end of this week, if there is an interest in integration with ceres for all groups.

**Comment by sergiud** [comment]
Great (I kind of missed your PR)! Does it make sense to finish the `LocalParameterization` implementation first and then move to `Manifold` in a subsequent PR?

**Comment by DmitriyKorchemkin** [comment]
I've rebased pull-request #305 onto current master branch.
It contains a full solution for `ceres::LocalParameterization`; I think that implementation for `ceres::Manifold` would be +- independent of it.

**Comment by strasdat** [comment]
https://github.com/strasdat/Sophus/pull/355
