### ISSUE TITLE
Make errors in test_sim2.cpp

### ISSUE THREAD

**Issue by Timbersaw-wangzw** [strasdat/Sophus#339]
when i make the Sophus library, there were some errors and listed part of them above. I tried to add `TARGET_LINK_LIBRARIES( ${test_src} sophus fmt::fmt-header-only)` in  test/core/CMakeLists.txt. But it failed, can you figure out how to solve it? THANKS!
```
[  4%] Building CXX object test/core/CMakeFiles/test_sim2.dir/test_sim2.cpp.o
In file included from /home/wangziwei/Sophus/sophus/common.hpp:36:0,
                 from /home/wangziwei/Sophus/sophus/types.hpp:8,
                 from /home/wangziwei/Sophus/sophus/rotation_matrix.hpp:10,
                 from /home/wangziwei/Sophus/sophus/so2.hpp:13,
                 from /home/wangziwei/Sophus/sophus/rxso2.hpp:7,
                 from /home/wangziwei/Sophus/sophus/sim2.hpp:7,
                 from /home/wangziwei/Sophus/test/core/test_sim2.cpp:5:
/usr/local/include/fmt/core.h: In instantiation of ‘constexpr fmt::v8::detail::value<Context> fmt::v8::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; fmt::v8::detail::type <anonymous> = (fmt::v8::detail::type)15; T = const Eigen::Matrix<double, 2, 2>&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’:
/usr/local/include/fmt/core.h:1839:77:   required from ‘constexpr fmt::v8::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const Eigen::Matrix<double, 2, 2, 0, 2, 2>&}; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; Args = {Eigen::Matrix<double, 2, 2, 0, 2, 2>}]’
/usr/local/include/fmt/core.h:3216:15:   required from ‘void fmt::v8::print(fmt::v8::format_string<T ...>, T&& ...) [with T = {const Eigen::Matrix<double, 2, 2, 0, 2, 2>&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const Eigen::Matrix<double, 2, 2, 0, 2, 2>&>]’
/home/wangziwei/Sophus/sophus/rxso2.hpp:388:5:   required from ‘void Sophus::RxSO2Base<Derived>::setScaledRotationMatrix(const Transformation&) [with Derived = Sophus::RxSO2<double>; Sophus::RxSO2Base<Derived>::Transformation = Eigen::Matrix<double, 2, 2>; typename Eigen::internal::traits<T>::Scalar = double]’
```

**Comment by sergiud** [comment]
You left out the error. Please post the full log.

**Comment by Timbersaw-wangzw** [comment]
I followed the indications to make Sophus. It works!

> The fmt dependency can be eliminated by passing "-DUSE_BASIC_LOGGING=ON" to cmake when configuring Sophus

but i make my own project. The errors related by **fmt** occured! The log were:
`In file included from /usr/local/include/sophus/common.hpp:36:0,
                 from /usr/local/include/sophus/types.hpp:8,
                 from /usr/local/include/sophus/rotation_matrix.hpp:10,
                 from /usr/local/include/sophus/so3.hpp:7,
                 from /usr/local/include/sophus/se3.hpp:7,
                 from /home/wangziwei/pcl_test/src/../include/complement_lie.h:9,
                 from /home/wangziwei/pcl_test/src/../include/ipopt_registration.h:21,
                 from /home/wangziwei/pcl_test/src/ipopt_registration.cpp:10:
/usr/local/include/fmt/core.h: In instantiation of ‘fmt::v8::detail::value<Context> fmt::v8::detail::make_arg(T&&) [with bool IS_PACKED = true; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; fmt::v8::detail::type <anonymous> = (fmt::v8::detail::type)15; T = const Eigen::Transpose<const Eigen::Matrix<float, 3, 1> >&; typename std::enable_if<IS_PACKED, int>::type <anonymous> = 0]’:
/usr/local/include/fmt/core.h:1839:77:   required from ‘fmt::v8::format_arg_store<Context, Args>::format_arg_store(T&& ...) [with T = {const Eigen::Transpose<const Eigen::Matrix<float, 3, 1, 0, 3, 1> >&, float&, float&}; Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; Args = {Eigen::Transpose<const Eigen::Matrix<float, 3, 1, 0, 3, 1> >, float, float}]’
/usr/local/include/fmt/core.h:1856:38:   required from ‘constexpr fmt::v8::format_arg_store<Context, fmt::v8::remove_cvref_t<Args>...> fmt::v8::make_format_args(Args&& ...) [with Context = fmt::v8::basic_format_context<fmt::v8::appender, char>; Args = {const Eigen::Transpose<const Eigen::Matrix<float, 3, 1, 0, 3, 1> >&, float&, float&}]’
/usr/local/include/fmt/core.h:3216:44:   required from ‘void fmt::v8::print(fmt::v8::format_string<T ...>, T&& ...) [with T = {const Eigen::Transpose<const Eigen::Matrix<float, 3, 1, 0, 3, 1> >, float&, float&}; fmt::v8::format_string<T ...> = fmt::v8::basic_format_string<char, const Eigen::Transpose<const Eigen::Matrix<float, 3, 1, 0, 3, 1> >, float&, float&>]’
/usr/local/include/sophus/so3.hpp:692:5:   required from ‘static Sophus::SO3<Scalar_> Sophus::SO3<Scalar_, Options>::expAndTheta(const Tangent&, Sophus::SO3<Scalar_, Options>::Scalar*) [with Scalar_ = float; int Options = 0; Sophus::SO3<Scalar_, Options>::Tangent = Eigen::Matrix<float, 3, 1>; Sophus::SO3<Scalar_, Options>::Scalar = float]’
/usr/local/include/sophus/se3.hpp:832:53:   required from ‘static Sophus::SE3<Scalar_> Sophus::SE3<Scalar_, Options>::exp(const Tangent&) [with Scalar_ = float; int Options = 0; Sophus::SE3<Scalar_, Options>::Tangent = Eigen::Matrix<float, 6, 1, 0, 6, 1>]’
/home/wangziwei/pcl_test/src/ipopt_registration.cpp:156:48:   required from here
/usr/local/include/fmt/core.h:1711:3: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
   static_assert(
   ^~~~~~~~~~~~~
bin/CMakeFiles/test_pcl.dir/build.make:62: recipe for target 'bin/CMakeFiles/test_pcl.dir/ipopt_registration.cpp.o' failed
make[2]: *** [bin/CMakeFiles/test_pcl.dir/ipopt_registration.cpp.o] Error 1
CMakeFiles/Makefile2:85: recipe for target 'bin/CMakeFiles/test_pcl.dir/all' failed
make[1]: *** [bin/CMakeFiles/test_pcl.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2`
How to solve these problems? I assume i should remove the fmt dependency by some specific code! THANKS!
