### ISSUE TITLE
Error using Sophus

### ISSUE THREAD

**Issue by franciscodominguezmateos** [strasdat/Sophus#34]
Hello
I am trying Sophus in other machine with ROS indigo Ubuntu 14.04 64bits.
When I try to compile this code, with eclipse and using only includes no linking:
# include <iostream>
# include "sophus/se3.hpp"

using namespace std;

typedef double Scalar;
typedef Sophus::SO3Group<Scalar> SO3Type;
typedef typename Sophus::SO3Group<Scalar>::Point Point;
typedef typename Sophus::SO3Group<Scalar>::Tangent Tangent;

int main() {
    cout << "!!!Hello World!!!" << endl; // prints !!!Hello World!!!
    return 0;
}
I get this error:
     Scalar length = unit_quaternion_nonconst().norm();
     ^
/home/francisco/git/Sophus/sophus/so3.hpp:216:12: error: expected ‘;’ before ‘length’
     Scalar length = unit_quaternion_nonconst().norm();
Any idea? It is a issue?

**Comment by strasdat** [comment]
I can only support master builds here; not versions (e.g. ROS indigo).
