### ISSUE TITLE
Disable Eigen alignment and Sophus starts crashing with EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by santevid** [strasdat/Sophus#344]
I have a project that is using Eigen and Sophus, I have disabled Eigen alignment by defining a compiler flag "-DEIGEN_MAX_ALIGN_BYTES=0" and I can confirm that alignment in Eigen is disabled (more about Eigen alignment https://eigen.tuxfamily.org/dox/TopicPreprocessorDirectives.html). However, it seems that Sophus which uses Eigen internally, still tries to do Eigen alignment.

How to repro !?
Create a simple class with Eigen::Dynamic member matrices as well as Sophus:SE3 member var, try to modify those vars, use operator= etc. at one point Sophus will throw EXC_BAD_ACCESS due memory alignment issue

**Comment by NikolausDemmel** [comment]
This sounds like a build system issue where the compiler flag is maybe not properly set for all translation units. You'll probably have to provide a full reproducible example including build system files to get help for this.

It doesn't look like Sophus is doing anything special w.r.t. alignment except for use of `EIGEN_MAKE_ALIGNED_OPERATOR_NEW`.
