### ISSUE TITLE
Update the tests to look for Ceres 2.1.0

### ISSUE THREAD

**Issue by MartinEekGerhardsen** [strasdat/Sophus#359]
**Describe the bug**
When compiling Sophus against Ceres version 2.0.0, the compilation of the Ceres test targets fails because the <ceres/manifold.h> header file doesn't exist. 

```
Sophus/sophus/ceres_manifold.hpp:3:10: fatal error: ceres/manifold.h: No such file or directory
 #include <ceres/manifold.h>
```

**To Reproduce**
[Steps to reproduce the behavior:]
1. Install Ceres 2.0.0
2. Clone Sophus v22.04.1 (or 
3. Compile Sophus. This then fails as described above. 

**Expected behavior**
Looking at the CMakeLists.txt for ceres test, I assume that this code is not supposed to be compiled at all unless you have Ceres (and especially the correct version) installed. For a system with Ceres, though without the new manifold code, I would expect the code to ignore the compilation of this test and not crash. 

**Sophus version: commit hash**

785fef35b7d9e0fc67b4964a69124277b7434a44

**Additional context**

**Comment by strasdat** [comment]
#360
