### ISSUE TITLE
Question with ceres LocalParameterization

### ISSUE THREAD

**Issue by DavidLee999** [strasdat/Sophus#364]
Guys, I'd like to do pose graph optimization using ceres-solver with Sophus.

While using Sophus::SE3d to represent pose T, I am using the `data()` method to get the raw data of the pose T. And the raw data the method return is stored as  `(q, t)`, where `q` represents the rotation part and `t` is the translation part. 

So when you do the optimization, the computed udpate lie algebra `delta_T` is stored as `(\phi, \rho)`, where `\phi` is the roation part and `\rho` is the translation part. To update the pose T, the `Plus()` method would be implemented as `T * exp(delta_T)`.

However, the `exp(Tangent const &a)` method require that the first three components of `a` should be the translation part and the last three components of `a` should be the rotation part, which is opposite with the `data()` method.  So I think it needs to change the order of `delta_T` in order to do the plus.

But in the [LocalParameterization](https://github.com/strasdat/Sophus/blob/master/sophus/ceres_local_parameterization.hpp), the author uses the `exp()` method directly with the `delta_raw` variable. Is there a bug or it change the order of `T_raw` in advance?

**Comment by DmitriyKorchemkin** [comment]
@DavidLee999 ,
The order of rotational and translational parts of increment does not matter as long as it is consistent with jacobian (returned by `LocalParameterization::ComputeJacobian` method, which uses `SE3::Dx_this_mul_exp_x_at_0` method).
Reordering translational and rotational parts of the increment will reorder columns of that jacobian, and reordering translational and rotational parts of the group element will reorder rows of that jacobian.

While it might be hard to notice from the implementation ( https://github.com/strasdat/Sophus/blob/master/sophus/se3.hpp#L135-L204 ), but at least you may note that 4x3 top-left corner  of matrix returned by this method is zero (corresponding to derivatives of rotation by translational part).


Correctness of `Dx_this_mul_exp_x_at_0` with relation to `exp` method is verified by tests around these lines https://github.com/strasdat/Sophus/blob/master/test/core/tests.hpp#L227-L236

**Comment by DavidLee999** [comment]
> @DavidLee999 , The order of rotational and translational parts of increment does not matter as long as it is consistent with jacobian (returned by `LocalParameterization::ComputeJacobian` method, which uses `SE3::Dx_this_mul_exp_x_at_0` method). Reordering translational and rotational parts of the increment will reorder columns of that jacobian, and reordering translational and rotational parts of the group element will reorder rows of that jacobian.
> 
> While it might be hard to notice from the implementation ( https://github.com/strasdat/Sophus/blob/master/sophus/se3.hpp#L135-L204 ), but at least you may note that 4x3 top-left corner of matrix returned by this method is zero (corresponding to derivatives of rotation by translational part).
> 
> Correctness of `Dx_this_mul_exp_x_at_0` with relation to `exp` method is verified by tests around these lines https://github.com/strasdat/Sophus/blob/master/test/core/tests.hpp#L227-L236

You are right. Thank you for clear explanation.
