### ISSUE TITLE
Could NOT find Eigen3 with cmake 3.22, eigen 3.4.0, VS 2019

### ISSUE THREAD

**Issue by fengweichangzi** [strasdat/Sophus#374]
When I tried to build Sophus with cmake, I got the following errors:
```
CMake Error at D:/Program Files/cmake-3.22.5-windows-x86_64/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Eigen3 (missing: EIGEN3_VERSION_OK) (Required is at least  version "3.3.0")
```

Then I checked some other questions, I found commenting this in line 46 in CMakeLists.txt will work
`list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake_modules")`

After that, I could configure and generate Sophus successfully.

I did not know whether commenting will cause some side effect, maybe the CMakeLists.txt should be updated with commenting the above info.

**Comment by fengweichangzi** [comment]
Well, after generate sucessfully, I got errors when I tried to build them with VS2019.

`Error	C2338	Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt	HelloSO3	D:\3rdparty\fmt-9.1.0\include\fmt\core.h	1757	Build	`

It seemed froom FMT library, but I do not know how to fix it?

**Comment by fengweichangzi** [comment]
Now I figured it out.
1st, it is no need to build and compile Sophus source files, just include the .hpp files
2nd, make sure including Eigen files
3rd, build fmt and add it to your project
       Be attention to the version, I made it with fmt 8.1.1 while failed with fmt 9.1.0

**Comment by DmitriyKorchemkin** [comment]
@fengweichangzi , if you have spare time - could you please try again with fmt 9.1.0 and pull-request #376  applied?

**Comment by strasdat** [comment]
#376 is merged.

**Comment by fengweichangzi** [comment]
Very good!
I triy the latest master version and it works now with fmt 9.1.0.
