### ISSUE TITLE
QuaternionProduct in So3.hpp missing SOPHUS_FUNC

### ISSUE THREAD

**Issue by rohanchabra** [strasdat/Sophus#422]
**Describe the bug**
QuaternionProduct in So3.hpp missing SOPHUS_FUNC
**To Reproduce**
Bug will be reproduced on device code

**Expected behavior**
QuaternionProduct can be called from device code

**Sophus version: commit hash**

master 5c97c7d56130334e0a7a61db5e0e6cde82dc96a8

**Comment by strasdat** [comment]
fixed

#423
