### ISSUE TITLE
SOPHUS_FMT_ARG causes compilization error when SOPHUS_USE_BASIC_LOGGING=ON

### ISSUE THREAD

**Issue by dzywater** [strasdat/Sophus#436]
I think:
https://github.com/strasdat/Sophus/blob/1cba0d82cd224c7b3694d601f8c9cddc0876b42b/sophus/common.hpp#L21
#define SOPHUS_FMT_ARG(arg)
should be 
#define SOPHUS_FMT_ARG(arg) arg
instead

**Comment by nachovizzo** [comment]
Opened #502 with the fix, hopefully they will merge it soonish

**Comment by zjsyj** [comment]
this bug is still there
Sophus version: 1.22.10
OS: windows  10.0.22621.1778
Compiler: cl.exe 19.29

**Comment by strasdat** [comment]
This should be fixed by #538, since it removes BASIC_LOGGING and the fmt dependency and includes corresponding CI coverage.
