### ISSUE TITLE
leftJacobian implementation cannot echo the formula in given PDF

### ISSUE THREAD

**Issue by dzywater** [strasdat/Sophus#439]
https://github.com/strasdat/Sophus/blob/caf27cf918b180852f55e4395139aa30397ed0a2/sophus/so3.hpp#L566 

      V = Matrix3<Scalar>::Identity() +
          (Scalar(1) - cos(theta)) / theta_sq * Omega +
          (theta - sin(theta)) / (theta_sq * theta) * Omega_sq;

Based on http://asrl.utias.utoronto.ca/~tdb/bib/barfoot_ser17_identities.pdf.
The  Matrix3<Scalar>::Identity()  should multiply by sin(theta)/theta.

**Comment by NikolausDemmel** [comment]
I think both are correct. Note that $\mathbf{a}$ in the report corresponds to `omega / theta` in the code. You can see the equivalence using the identity $\hat{\mathbf{a}}^2 = \mathbf{a} \mathbf{a}^\top - I$.

More practically, we have the [same variant of the formula in Basalt](https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/86ebcf48df350d9332103971299009fc7a66d0ef/include/basalt/utils/sophus_utils.hpp#L349-356) and a [unit test that verifies the Jacobian numerically](https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/86ebcf48df350d9332103971299009fc7a66d0ef/test/src/test_sophus.cpp#L78-95).

It is my understanding that the version of the formula in the code, while analytically equivalent, has better numerics.

**Comment by dzywater** [comment]
> I think both are correct. Note that a in the report corresponds to `omega / theta` in the code. You can see the equivalence using the identity a^2=aa⊤−I.
> 
> More practically, we have the [same variant of the formula in Basalt](https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/86ebcf48df350d9332103971299009fc7a66d0ef/include/basalt/utils/sophus_utils.hpp#L349-356) and a [unit test that verifies the Jacobian numerically](https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/86ebcf48df350d9332103971299009fc7a66d0ef/test/src/test_sophus.cpp#L78-95).
> 
> It is my understanding that the version of the formula in the code, while analytically equivalent, has better numerics.

I transform the formula in the report.
![1](https://user-images.githubusercontent.com/22073470/210291033-86b20888-9341-41f0-ade7-b5ac78e03c37.png)

The code is actually
I cannot undertand why (3) is equivalent with (4).
![2](https://user-images.githubusercontent.com/22073470/210291041-2fbfb68c-b320-44d4-b8b5-d0a7594d21bb.png)

What do I miss?

**Comment by dzywater** [comment]
> I think both are correct. Note that a in the report corresponds to `omega / theta` in the code. You can see the equivalence using the identity a^2=aa⊤−I.
> 
> More practically, we have the [same variant of the formula in Basalt](https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/86ebcf48df350d9332103971299009fc7a66d0ef/include/basalt/utils/sophus_utils.hpp#L349-356) and a [unit test that verifies the Jacobian numerically](https://gitlab.com/VladyslavUsenko/basalt-headers/-/blob/86ebcf48df350d9332103971299009fc7a66d0ef/test/src/test_sophus.cpp#L78-95).
> 
> It is my understanding that the version of the formula in the code, while analytically equivalent, has better numerics.

Thanks. I got it.
