### ISSUE TITLE
Broken link on landing page README.rst

### ISSUE THREAD

**Issue by zbuilder** [strasdat/Sophus#470]
**Describe the bug**
[A clear and concise description of what the bug is.]
The landing page https://github.com/strasdat/Sophus displays a documentation page README.rst with broken link
https://strasdat.github.io/Sophus/.  The error message is:

```
404
File not found

The site configured at this address does not contain the requested file.

If this is your site, make sure that the filename case matches the URL.
For root URLs (like http://example.com/) you must provide an index.html file.
```

[Read the full documentation](https://help.github.com/pages/) for more information about using GitHub Pages.

**To Reproduce**
[Steps to reproduce the behavior:]
1. Visit https://github.com/strasdat/Sophus
2. Click on hyperlink https://strasdat.github.io/Sophus/
3. 

**Expected behavior**
[A clear and concise description of what you expected to happen.]
Link should take reader to a working URL.

**Sophus version: commit hash**

[Commit hash on main branch which has the bug. Please test on HEAD of main first before submitting a bug.]
d9610ad5536bd601d42df0d33a3abdff9456679c

**Additional context**

**Comment by strasdat** [comment]
Thanks for reporting!

**Comment by altaykacan** [comment]
Issue #514  is about the same problem. As I sent there, I found that this link works: https://strasdat.github.io/Sophus/latest/

I'm not sure if it is completely finished though.

**Comment by strasdat** [comment]
This won't be fixed unfortunately, since it is too much of a maintenance burden. Please refer to the in code comments as a documentation. all docs links / folders will be removed as part of #538.
