### ISSUE TITLE
install erorr issue

### ISSUE THREAD

**Issue by mleplawy** [strasdat/Sophus#508]
I'm trying to install on ubuntu bot there is problem like below install error issue

@ubuntu:~/Sophus/build$ make install
[  7%] Built target test_geometry
[ 14%] Built target test_velocities
[ 21%] Built target test_so2
[ 28%] Built target test_cartesian2
[ 35%] Built target test_sim2
[ 42%] Built target test_cartesian3
[ 50%] Built target test_common
[ 53%] Building CXX object test/core/CMakeFiles/test_rxso3.dir/test_rxso3.cpp.o
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
test/core/CMakeFiles/test_rxso3.dir/build.make:62: recipe for target 'test/core/CMakeFiles/test_rxso3.dir/test_rxso3.cpp.o' failed
make[2]: *** [test/core/CMakeFiles/test_rxso3.dir/test_rxso3.cpp.o] Error 4
CMakeFiles/Makefile2:421: recipe for target 'test/core/CMakeFiles/test_rxso3.dir/all' failed
make[1]: *** [test/core/CMakeFiles/test_rxso3.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by strasdat** [comment]
I aim to add some "install tests". Hopefully/possible as part of #538.
