### ISSUE TITLE
SOPHUS_USE_BASIC_LOGGING=ON compilation error

### ISSUE THREAD

**Issue by Lishen1** [strasdat/Sophus#516]
**Describe the bug**
[A clear and concise description of what the bug is.]

**To Reproduce**
turn on SOPHUS_USE_BASIC_LOGGING=ON 
build on windows msvc

```#define SOPHUS_ENSURE(expr, ...)                                              \
  do {                                                                        \
    if (!(expr)) {                                                            \
      SOPHUS_DEDAULT_ENSURE_FAILURE_IMPL(SOPHUS_FUNCTION, __FILE__, __LINE__, \
                                         ##__VA_ARGS__);                      \
    }                                                                         \
  } while (false)
#endif
```
as i think here (and next too) should be #__VA_ARGS__ (stringification) instead of ##__VA_ARGS__ (concatination)
at least it fix compilation errors
**Expected behavior**
[A clear and concise description of what you expected to happen.]

**Sophus version: commit hash**
commit 61f9a9815f7f5d4d9dcb7f4ad9f4f42ab3563108 (grafted, HEAD, origin/main-1.x, origin/HEAD, main-1.x)
[Commit hash on main branch which has the bug. Please test on HEAD of main first before submitting a bug.]

**Additional context**

**Comment by strasdat** [comment]
This should be fixed by #538, since it removes BASIC_LOGGING and the fmt dependency and includes corresponding CI coverage.
