### ISSUE TITLE
FMT warning when not found

### ISSUE THREAD

**Issue by Kikadass** [strasdat/Sophus#520]
**Describe the bug**
When linking the library and fmt is not installed a warning appears:
![image](https://github.com/strasdat/Sophus/assets/15006324/a5bd688c-7b2c-4e28-b55d-1de3513b8786)

**To Reproduce**
[Steps to reproduce the behavior:]
1. Link the library with cmake.

In my case I am adding sophus as a third party library with FetchContent:
```
include(FetchContent)
FetchContent_Declare(
  sophus_install
  URL https://github.com/strasdat/Sophus/archive/refs/tags/1.22.10.tar.gz
)
FetchContent_MakeAvailable(sophus_install)
```

**Expected behavior**
fmt is not required, therefor, it should find package in QUIET mode.
find_package(fmt QUIET)

**Sophus version: 1.22.10**

**Comment by strasdat** [comment]
This should be fixed by #538, since it removes the fmt dependency.
