### ISSUE TITLE
CUDA::cublas but the target was not found

### ISSUE THREAD

**Issue by Echo-gh** [strasdat/Sophus#523]
cmake error:
"""
CMake Error at /usr/local/lib/cmake/Ceres/CeresTargets.cmake:59 (set_target_properties):
  The link interface of target "Ceres::ceres" contains:

    CUDA::cublas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:272 (include)
  test/core/CMakeLists.txt:15 (find_package)

CMake Error at /usr/local/lib/cmake/Ceres/CeresTargets.cmake:59 (set_target_properties):
  The link interface of target "Ceres::ceres" contains:

    CUDA::cublas

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  /usr/local/lib/cmake/Ceres/CeresConfig.cmake:272 (include)
  test/ceres/CMakeLists.txt:5 (find_package)
"""

Ceres version: 2.1.0
CUDA version: 11.2

I cannot find any useful information. Please tell me how to fix it. Thanks!

**Comment by Echo-gh** [comment]
I solved it by reinstall Ceres.

**Comment by Cureser** [comment]
Could you tell me which version Ceres you reinstall?
