### ISSUE TITLE
Sophus ensure failed in function .....

### ISSUE THREAD

**Issue by rosrookie** [strasdat/Sophus#530]
When I try to use Eigen to create SO3, and to calculate SO3 -> so3, and so3 -> SO3. it's just a demo.

Here is my code:

```c++
#include <Eigen/Geometry>
#include <Eigen/Core>
#include <sophus/se3.hpp>
#include <sophus/so3.hpp>

#include <iostream>
#include <cmath>

using namespace std;
using namespace Eigen;

int main(int argc, char **argv)
{

    double angle = 0.524; // rad.  30°
    Vector3d w_s(0, 0.866, 0.5);

    Matrix3d R = Matrix3d::Zero();

    // create a rot matrix.
    R = AngleAxisd(angle, w_s).toRotationMatrix();

    cout.precision(3);
    cout << fixed << "Matrix made by Rodrigues formula: \n"
         << R << endl;

    // give matrix to SO3
    Sophus::SO3d SO3_R(R);

    cout << SO3_R.matrix() << endl;

    // SO3 -> so3
    Vector3d so3 = SO3_R.log();

    cout << "so3: \n"
         << fixed << so3 << endl; // it should be (0, 0.453, 0.262)

    // This is another test. so3 -> SO3
    Vector3d v(0, 0.453, 0.262);
    Sophus::SO3d SO3;
    SO3 = Sophus::SO3d::exp(v);

    cout << "so3 -> SO3: \n"
         << SO3.matrix() << endl;

    return 0;
}
```

well, then the compiler did not report an error.  So I run it , but here is comes error, I dont know what happend.

```bash
Matrix made by Rodrigues formula: 
 0.866 -0.250  0.433
 0.250  0.966  0.058
-0.433  0.058  0.899
Sophus ensure failed in function 'Sophus::SO3<Scalar_, Options>::SO3(const Transformation&) [with Scalar_ = double; int Options = 0; Sophus::SO3<Scalar_, Options>::Transformation = Eigen::Matrix<double, 3, 3>]', file '/usr/local/include/sophus/so3.hpp', line 517.
R is not orthogonal:
     0.999989  6.93889e-18 -5.55112e-17
 6.93889e-18     0.999988 -3.42993e-07
-5.55112e-17 -3.42993e-07     0.999989
Aborted (core dumped)
```

BTW:
here is my CMakeLists.txt

```cmake
cmake_minimum_required(VERSION 3.0.2)
project(sophus_demo)

find_package(Eigen3 REQUIRED COMPONENTS SHARED)
find_package(Sophus REQUIRED COMPONENTS SHARED)
find_package(FMT REQUIRED COMPONENTS SHARED)

include_directories(${Sophus_INCLUDE_DIRS})
include_directories(${fmt_INCLUDE_DIRS})

add_executable(demo1 demo1.cpp)
target_link_libraries(demo1 ${Sophus_LIBRARIES} fmt::fmt)
```

And I use this way to install Sophus:

```bash
sudo apt install libfmt-dev
git clone https://github.com/strasdat/Sophus.git
cd Sophus
mkdir build
cd build
cmake ..
make -j8
sudo make install
```
well, my OS is ubuntu 20.04

Thanks!

**Comment by fwcore** [comment]
Converting from rotation matrix to `Sophus::SO3` subjects to checking whether the matrix is orthogonal by computing norm(R*R^T - I) < epsilon. See
https://github.com/strasdat/Sophus/blob/d270df2be6e46501b1e7efc09b107517e0be0645/sophus/so3.hpp#L511-L521
and
https://github.com/strasdat/Sophus/blob/d270df2be6e46501b1e7efc09b107517e0be0645/sophus/rotation_matrix.hpp#L16-L26

This checking is affected by numeric precision. The `epsilon` for `double` is 1e-10, while for `float`, it's 1e-5.
https://github.com/strasdat/Sophus/blob/d270df2be6e46501b1e7efc09b107517e0be0645/sophus/common.hpp#L157
and
https://github.com/strasdat/Sophus/blob/d270df2be6e46501b1e7efc09b107517e0be0645/sophus/common.hpp#L174-L177

As your error message shows, the matrix R*R^T is
```
     0.999989  6.93889e-18 -5.55112e-17
 6.93889e-18     0.999988 -3.42993e-07
-5.55112e-17 -3.42993e-07     0.999989
```
which has largest off-diagonal element in the order of 1e-7, which is much larger than `epsilon` for double (1e-10).

As a workaround, one can convert rotation matrix to float SO3, and then cast to double:
```c++
    // give matrix to SO3
    Sophus::SO3d SO3_R =  Sophus::SO3f(R).cast<double>();
```

**Comment by strasdat** [comment]
@rosrookie, @fwcore you can just call

```
Sophus::SO3d::fitToSO3(R);
``` 

instead of 

```
Sophus::SO3d(R);
```
