### ISSUE TITLE
sophus

### ISSUE THREAD

**Issue by xyh2211** [strasdat/Sophus#536]
![image](https://github.com/strasdat/Sophus/assets/129502097/2a2fa335-1135-43d2-adf5-6de1681a9a83)为什么我切换分支无法成功，git checkout a621ff,然后我跳过这一步骤，直接编译，最终在catkin_make代码的时候，Sophus总是报错。

**Comment by versatran01** [comment]
It tells you to use `catkin_make_isolated` instead

**Comment by strasdat** [comment]
please file bug upstream with e.g. ROS
