### ISSUE TITLE
404 for site `https://strasdat.github.io/Sophus/latest/`

### ISSUE THREAD

**Issue by chenrui333** [strasdat/Sophus#547]
👋 looks like the site `https://strasdat.github.io/Sophus/latest/` is gone? 

also, can you mark the 1.24.6 as latest release? Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/174413

**Comment by strasdat** [comment]
Yeah, that link is dead - no fix planned. If you need a weblink, I'd suggest just: https://github.com/strasdat/Sophus

**Comment by strasdat** [comment]
@chenrui333 
Apologies, 1.24.6 was created by default, only existed for a few hours and does not exist anymore. But we do have:

https://github.com/strasdat/Sophus/releases/tag/1.24.6-rc1

And there will be a proper 1.24.6 soon. I hope I did not break any tools on your end...

**Comment by chenrui333** [comment]
> Yeah, that link is dead - no fix planned. If you need a weblink, I'd suggest just: https://github.com/strasdat/Sophus

yeah, I will use that.



> Apologies, 1.24.6 was created by default, only existed for a few hours and does not exist anymore. But we do have:

totally, just closed my PR, thanks!

**Comment by strasdat** [comment]
@chenrui333 I just pushed the release, https://github.com/strasdat/Sophus/releases/tag/1.24.6

**Comment by chenrui333** [comment]
THanks @strasdat!
