### ISSUE TITLE
Build Error 

### ISSUE THREAD

**Issue by ahmet-f-gumustas** [strasdat/Sophus#549]
**Describe the bug**
I am currently using Ubuntu 22.04
Clone this repostory and :
mkdir build / cd build / cmake .. / make

and gave me some error 

moveon2@moveon2-asus-tuf:~/workspace/Sophus/build$ make
[  5%] Built target test_common
[ 10%] Built target test_cartesian2
[ 15%] Built target test_cartesian3
[ 20%] Built target test_so2
[ 25%] Built target test_se2
[ 30%] Built target test_rxso2
[ 35%] Built target test_sim2
[ 40%] Built target test_so3
[ 45%] Built target test_se3
[ 50%] Built target test_rxso3
[ 55%] Built target test_sim3
[ 60%] Built target test_geometry
[ 62%] Building CXX object test/ceres/CMakeFiles/test_ceres_so3_manifold.dir/test_ceres_so3.cpp.o
In file included from /home/moveon2/workspace/Sophus/test/ceres/test_ceres_so3.cpp:5:
In file included from /home/moveon2/workspace/Sophus/test/ceres/tests.hpp:5:
/home/moveon2/workspace/Sophus/sophus/ceres_manifold.hpp:3:10: fatal error: 'ceres/manifold.h' file not found
#include <ceres/manifold.h>
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [test/ceres/CMakeFiles/test_ceres_so3_manifold.dir/build.make:76: test/ceres/CMakeFiles/test_ceres_so3_manifold.dir/test_ceres_so3.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:506: test/ceres/CMakeFiles/test_ceres_so3_manifold.dir/all] Error 2
make: *** [Makefile:146: all] Error 2

This is the error !

How to solve this

**Comment by strasdat** [comment]
It seems to be the wrong ceres version (or missing ceres install and a bug in the cmake script). The one which works for sure is:

```
git clone https://ceres-solver.googlesource.com/ceres-solver ceres-solver
cd ceres-solver
git reset --hard 6a74af202d83cf31811ea17dc66c74d03b89d79e
```

Do you have any version of ceres installed?

**Comment by ahmet-f-gumustas** [comment]
@strasdat 

Hey sir I try every thing but gave me an same error !
