### ISSUE TITLE
Release numbers

### ISSUE THREAD

**Issue by ojwoodford** [strasdat/Sophus#55]
Hi Hauke

This project/repo is great. I think it would be super useful to have a release number, and to tag release commits. I think you had version 0.9 before. What do you say? Time for version 1.0.0?

Cheers,
Oliver

**Comment by strasdat** [comment]
Good idea, will look into this shortly.

**Comment by strasdat** [comment]
Okay, I pushed a tag for HEAD. I have a few changes I want to add (listed under Projects), before I want to move to 1.0.0.

**Comment by ojwoodford** [comment]
Great! Thanks, Hauke.

**Comment by zengbw** [comment]
About the release number, I would like to know if there will provide new version, such as 1.1 or anything else. As the version 1.0.0 has been released two years ago, does there any plans for new release version?
