### ISSUE TITLE
Vectorization

### ISSUE THREAD

**Issue by ibtaylor** [strasdat/Sophus#72]
Hi, thanks for writing Sophus!

This is less of an issue, and more of a comment about the implementation.

I'm wanting to interpolate with `SE3`, but I'm seeing some performance problems. From looking at the assembly and the [eigen docs](http://eigen.tuxfamily.org/index.php?title=FAQ#What_can.27t_be_vectorized.3F), it doesn't appear that `SE3` operations are vectorized very well or at all.

I think there could be great performance benefits to having `SO3` use a `Vector4` and `Matrix4` internally.
Same for `SE3`.

Interpolating with `Sim3`, I see a `~64x` performance improvement over `SE3`. However, it seems like even `Sim3` could make better use of Eigen's vectorization if it instead used vectors and matrices with dimensions that were multiples of 4.

It seems okay that the `operator*` takes a `Vector3` as long as a `Matrix4` or `Matrix3x4` is available via `matrix()`.

I'd much rather not use `Sim3` because I'm not dealing with scale, but I'll probably end up using it due to performance reasons.

**Comment by strasdat** [comment]
Hey, ibtaylor. Are you saying that interpolation using Sim3 is 64 times faster when using SE3? This is surprising; this can't be explained by vectorization alone; there is probably a real performance bug somewhere.

To approach this systematical I think it is time to add some performance test suit to the Sophus CI. Can you send me a minimal complete example where you measured the performance difference between Sim3 and SE3?

**Comment by strasdat** [comment]
In other words, I'm note against the idea of enabling more vectorization in Sophus. But I think we should start with performance metrics on CI so we understand what we gain or loose when making such implementation changes.

**Comment by ibtaylor** [comment]
@strasdat here is a really crudge benchmark. https://gist.github.com/ibtaylor/63a54a30cb5ca85e92c60c899d44c264
I'm writing the results to a file just so some stuff doesn't get optimized away by the compiler.

Sophus version: `https://github.com/strasdat/Sophus/archive/eb869eff9eb8a7d783eb0f62b85292a38b93430b.tar.gz`
Eigen version: `http://bitbucket.org/eigen/eigen/get/3.3.3.tar.bz2`
gcc version: `4.8.5 (Ubuntu 4.8.5-2ubuntu1~14.04.1)`

Do you get similar results?

**Comment by strasdat** [comment]
I can reproduce your results. Investigating...

**Comment by strasdat** [comment]
Alright, the logarithm of SE3 is the offender:

``
SE3: 0.39936s
Sim3: 0.012032s
se3_exp: 1.51533e-07s
se3_log: 3.96067e-05s
sim3_exp: 2.25691e-07s
sim3_log: 7.33744e-07s
``

**Comment by strasdat** [comment]
Interesting: ``std::tan(foo)`` seems to be much slower than ``sin(foo) / cos(foo)`` on my/our system.

**Comment by strasdat** [comment]
#77 should address it.

Before merging it in, however, I will test this more, especially with and without "--ffast-math".

**Comment by strasdat** [comment]
Okay, decided to merge it into the master branch. Will add some performance tests to CI in a follow-up.

**Comment by strasdat** [comment]
http://stackoverflow.com/questions/37504423/stdtan-extremely-slow-after-updating-glibc

**Comment by ibtaylor** [comment]
@strasdat much better now. thanks.
