### ISSUE TITLE
Control reaches end of non void function

### ISSUE THREAD

**Issue by UnexpectedGinger** [strasdat/Sophus#76]
I am using Eigen 3.0.5 and gcc 4.9. Whenever I try to compile sophus, I get the following error. I am trying to compile it in association with tum visions dvo_slam

` /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp:362:3: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp: In member function ‘Sophus::RxSO3Base<Derived>::Transformation Sophus::RxSO3Base<Derived>::rotationMatrix() const [with Derived = Sophus::RxSO3<float>; Sophus::RxSO3Base<Derived>::Transformation = Eigen::Matrix<float, 3, 3>; typename Eigen::internal::traits<T>::Scalar = float]’:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp:254:3: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp: In member function ‘Sophus::RxSO3<typename Eigen::internal::traits<T>::Scalar> Sophus::RxSO3Base<Derived>::inverse() const [with Derived = Sophus::RxSO3<float>; typename Eigen::internal::traits<T>::Scalar = float]’:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp:124:3: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp: In member function ‘const Eigen::Quaternion<Scalar_>& Sophus::RxSO3<Scalar_, Options>::quaternion() const [with Scalar_ = float; int Options = 0]’:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp:576:3: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
  In file included from /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp:4:0,
                   from /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/test/core/test_rxso3.cpp:3:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/so3.hpp: In static member function ‘static Sophus::SO3Base<Derived>::Tangent Sophus::SO3Base<Derived>::logAndTheta(const Sophus::SO3<typename Eigen::internal::traits<T>::Scalar>&, Sophus::SO3Base<Derived>::Scalar*) [with Derived = Sophus::SO3<float>; Sophus::SO3Base<Derived>::Tangent = Eigen::Matrix<float, 3, 1>; typename Eigen::internal::traits<T>::Scalar = float; Sophus::SO3Base<Derived>::Scalar = float]’:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/so3.hpp:455:3: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
  In file included from /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/test/core/test_rxso3.cpp:3:0:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp: In member function ‘Sophus::RxSO3Base<Derived>::Point Sophus::RxSO3Base<Derived>::operator*(const Point&) const [with Derived = Sophus::RxSO3<float>; Sophus::RxSO3Base<Derived>::Point = Eigen::Matrix<float, 3, 1>; typename Eigen::internal::traits<T>::Scalar = float]’:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/rxso3.hpp:211:3: error: control reaches end of non-void function [-Werror=return-type]
     }
     ^
  In file included from /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/test/core/tests.hpp:9:0,
                   from /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/test/core/test_rxso3.cpp:4:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/average.hpp: In function ‘Sophus::enable_if_t<std::is_same<typename SequenceContainer::value_type, Sophus::RxSO3<Scalar> >::value, Sophus::optional<typename SequenceContainer::value_type> > Sophus::average(const SequenceContainer&) [with SequenceContainer = std::array<Sophus::RxSO3<float>, 2u>; Scalar = float; Sophus::enable_if_t<std::is_same<typename SequenceContainer::value_type, Sophus::RxSO3<Scalar> >::value, Sophus::optional<typename SequenceContainer::value_type> > = Sophus::optional<Sophus::RxSO3<float> >]’:
  /home/devel/dvo_test/sandbox/dvo_slam/sophus/sophus_src/sophus/average.hpp:150:1: error: control reaches end of non-void function [-Werror=return-type]
   }`

**Comment by strasdat** [comment]
Can you try it with Eigen 3.3.3 and the latest version of Ceres (from the master branch)? This should work. (Or simply go back in time and use the version of Sophus which dvo_slam supports.)

**Comment by strasdat** [comment]
Eigen 3.0.5 is not supported; closing this out.
