### ISSUE TITLE
computation of scalar B in Sim3::exp

### ISSUE THREAD

**Issue by izhengfan** [strasdat/Sophus#79]
Hi, not sure if I was right but I have checked it for several times. It seems in the following line to compute scalar B using Taylor series in the case of  `theta->0`, the `-1` item as highlighted is dropped. Perhaps you could check it. 

https://github.com/strasdat/Sophus/blob/master/sophus/sim3.hpp#L330

I use `s` for scale, `s \theta` and `c \theta` for `sin` and `cos`, hope not making any confusion.

![image](https://cloud.githubusercontent.com/assets/8697363/23649407/4fcb482a-0359-11e7-93c5-01213b621ca9.png)

**Comment by strasdat** [comment]
Thanks, I will check this when I find some time :+1:

**Comment by strasdat** [comment]
Wow, it seems like Wolfram alpha agrees with you: http://www.wolframalpha.com/input/?i=((s+-+1)+%2F+sig+-+((s+*+cos(x)+-+1)+*+sig+%2B++s+*+sin(x)+*+x)+%2F+(x**2+%2B+sig**2))+*+1+%2F+(x**2)

Thanks for finding that! I will patch it soon. Only I have to do an investigation whether I need to enhance the unit test or tighten the test thresholds.

**Comment by izhengfan** [comment]
Good to hear that, thanks for your work!
