### ISSUE TITLE
[WIP] Python Wrapper

### ISSUE THREAD

**Issue by arntanguy** [strasdat/Sophus#83]
First of all, I'd like to thank you for all the incredible work that went on into Sophus, I use it into many projects.

Recently, I've been needing to do some quick prototyping, and as I got fed up with matlab, I decided to do it in python. Thus I started writing a small cython wrapper around Sophus to bring the magic of Lie algebra into python.

Here you go: https://github.com/arntanguy/PySophus

This is still a work in progress, but the most commonly needed functionalities are already implemented (exp, log, group product, and so on). It provides automatic conversion to/from numpy arrays.

As I don't have much time, I'll add functionalities on an as-needed basis, feel free to submit pull requests if you wish.

Best regards,
Arnaud

**Comment by strasdat** [comment]
Hey Arnaud, that's pretty cool! Thanks for sharing a link to your python wrapper. Currently, I'm not using python for numerical computation so I did not try it yet. 

 I'm happy to leave this issue open, so folks can find it from here.
