### ISSUE TITLE
Errors when using on Windows

### ISSUE THREAD

**Issue by arifle** [strasdat/Sophus#85]
Hi,

I was trying to compile a demo project which involves Sophus as the 3rdParty.  I have tried to compile Sophus with cmake before compiling the demo and testing projects are all ignored in cmake simply because those project cannot be compiled. Here is the error ouput of VS-2013. I don't know if you have any idea to deal with that. Just post an issue and maybe other people have the same problem. That project has only a line of include, #include <sophus/se3.hpp>.

I have added the include directory to the project in advance.

Thanks.

`c:\program files (x86)\sophus\include\sophus\common.hpp(146): error C2146: syntax error : missing ';' before identifier 'epsilon'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(146): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\common.hpp(146): warning C4183: 'epsilon': missing return type; assumed to be a member function returning 'int'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(150): error C2146: syntax error : missing ';' before identifier 'pi'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(150): error C2086: 'float Sophus::Constants<float>::constexpr' : redefinition
1>          c:\program files (x86)\sophus\include\sophus\common.hpp(146) : see declaration of 'Sophus::Constants<float>::constexpr'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(150): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\common.hpp(150): warning C4183: 'pi': missing return type; assumed to be a member function returning 'int'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(147): warning C4244: 'return' : conversion from 'float' to 'int', possible loss of data
1>c:\program files (x86)\sophus\include\sophus\common.hpp(150): warning C4244: 'return' : conversion from 'float' to 'int', possible loss of data
1>c:\program files (x86)\sophus\include\sophus\common.hpp(159): error C2146: syntax error : missing ';' before identifier 'nullopt_t'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(159): error C2071: 'Sophus::nullopt_t::constexpr' : illegal storage class
1>c:\program files (x86)\sophus\include\sophus\common.hpp(159): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\common.hpp(162): error C2146: syntax error : missing ';' before identifier 'nullopt_t'
1>c:\program files (x86)\sophus\include\sophus\common.hpp(162): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(76): error C2146: syntax error : missing ';' before identifier 'DoF'
1>          c:\program files (x86)\sophus\include\sophus\so3.hpp(491) : see reference to class template instantiation 'Sophus::SO3Base<Derived>' being compiled
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(76): error C2143: syntax error : missing ';' before '='
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(76): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(76): error C2238: unexpected token(s) preceding ';'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(78): error C2146: syntax error : missing ';' before identifier 'num_parameters'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(78): error C2086: 'int Sophus::SO3Base<Derived>::constexpr' : redefinition
1>          c:\program files (x86)\sophus\include\sophus\so3.hpp(76) : see declaration of 'Sophus::SO3Base<Derived>::constexpr'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(78): error C2143: syntax error : missing ';' before '='
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(78): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(78): error C2238: unexpected token(s) preceding ';'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(80): error C2146: syntax error : missing ';' before identifier 'N'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(80): error C2086: 'int Sophus::SO3Base<Derived>::constexpr' : redefinition
1>          c:\program files (x86)\sophus\include\sophus\so3.hpp(76) : see declaration of 'Sophus::SO3Base<Derived>::constexpr'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(80): error C2143: syntax error : missing ';' before '='
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(80): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(80): error C2238: unexpected token(s) preceding ';'
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(81): error C2065: 'N' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(83): error C2065: 'DoF' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(84): error C2065: 'DoF' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(123): error C2065: 'num_parameters' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(134): error C2065: 'num_parameters' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\so3.hpp(134): error C2065: 'DoF' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(64): error C2146: syntax error : missing ';' before identifier 'DoF'
1>          c:\program files (x86)\sophus\include\sophus\se3.hpp(494) : see reference to class template instantiation 'Sophus::SE3Base<Derived>' being compiled
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(64): error C2143: syntax error : missing ';' before '='
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(64): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(64): error C2238: unexpected token(s) preceding ';'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(67): error C2146: syntax error : missing ';' before identifier 'num_parameters'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(67): error C2086: 'int Sophus::SE3Base<Derived>::constexpr' : redefinition
1>          c:\program files (x86)\sophus\include\sophus\se3.hpp(64) : see declaration of 'Sophus::SE3Base<Derived>::constexpr'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(67): error C2143: syntax error : missing ';' before '='
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(67): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(67): error C2238: unexpected token(s) preceding ';'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(69): error C2146: syntax error : missing ';' before identifier 'N'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(69): error C2086: 'int Sophus::SE3Base<Derived>::constexpr' : redefinition
1>          c:\program files (x86)\sophus\include\sophus\se3.hpp(64) : see declaration of 'Sophus::SE3Base<Derived>::constexpr'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(69): error C2143: syntax error : missing ';' before '='
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(69): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(69): error C2238: unexpected token(s) preceding ';'
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(70): error C2065: 'N' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(72): error C2065: 'DoF' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(73): error C2065: 'DoF' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(100): error C2065: 'num_parameters' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(117): error C2065: 'num_parameters' : undeclared identifier
1>c:\program files (x86)\sophus\include\sophus\se3.hpp(117): error C2065: 'DoF' : undeclared identifier`

**Comment by scimg** [comment]
This is caused by constexpr, which is not supported by vs2013. Download vc_CompilerCTP.Nov2013.exe and upgrade your toolset will solve it partly.

**Comment by strasdat** [comment]
Yeah, Sophus does not support VS2013. Strictly speaking, it only supports the version which is used by AppVeyor, that is MSVC 19.0.24215.1. But it should work with all newer versions >= VS2015.
