### ISSUE TITLE
Which Eigen-Version use the branch tag v.0.9.5 

### ISSUE THREAD

**Issue by kevinkit** [strasdat/Sophus#93]
With which version was the branch tag v.0.9.5 designed?

Thank you

**Comment by strasdat** [comment]
Hey Kevin, not sure. My best guess would be to try libeigen-dev from Ubuntu 14.04, i.e. the corresponding Eigen version.

**Comment by kevinkit** [comment]
Thank you really much for your response, however I was able to resolve it in a different way. Thus, the issue could be closed - but since there is no answer to the question yet, I am not sure to wether do it

**Comment by strasdat** [comment]
"libeigen-dev from Ubuntu 14.04" will most likely work, so I'm closing this out
